#!/usr/bin/env python3
"""Extract font metrics from DejaVu TTF files and generate Rust static data.

Produces src/font_data.rs with compressed range-based advance lookup tables
that are byte-exact equivalent to ttf-parser runtime queries.
"""

import sys
from fontTools.ttLib import TTFont

FONTS = [
    ("DEJAVU_SANS",           "fonts/DejaVuSans.ttf"),
    ("DEJAVU_SANS_BOLD",      "fonts/DejaVuSans-Bold.ttf"),
    ("DEJAVU_MONO",           "fonts/DejaVuSansMono.ttf"),
    ("DEJAVU_MONO_BOLD",      "fonts/DejaVuSansMono-Bold.ttf"),
    ("DEJAVU_SERIF",          "fonts/DejaVuSerif.ttf"),
]


def extract_font(path):
    """Extract metrics from a single TTF file."""
    font = TTFont(path)
    head = font['head']
    hhea = font['hhea']
    os2 = font['OS/2']
    hmtx = font['hmtx']

    units_per_em = head.unitsPerEm
    ascender = hhea.ascent       # i16, positive
    descender = hhea.descent     # i16, negative
    typo_ascender = os2.sTypoAscender  # i16

    # Build codepoint -> advance mapping using the best cmap
    cmap = font.getBestCmap()
    cp_to_advance = {}
    for cp, glyph_name in cmap.items():
        adv, _lsb = hmtx[glyph_name]
        cp_to_advance[cp] = adv

    # Compress into ranges of consecutive codepoints with the same advance
    ranges = []
    sorted_cps = sorted(cp_to_advance.keys())
    if sorted_cps:
        start = sorted_cps[0]
        end = sorted_cps[0]
        adv = cp_to_advance[start]
        for cp in sorted_cps[1:]:
            cp_adv = cp_to_advance[cp]
            if cp == end + 1 and cp_adv == adv:
                end = cp
            else:
                ranges.append((start, end, adv))
                start = cp
                end = cp
                adv = cp_adv
        ranges.append((start, end, adv))

    font.close()
    return {
        'units_per_em': units_per_em,
        'ascender': ascender,
        'descender': descender,
        'typo_ascender': typo_ascender,
        'ranges': ranges,
        'num_codepoints': len(sorted_cps),
    }


def generate_rust(fonts_data):
    """Generate Rust source code from extracted data."""
    lines = []
    w = lines.append

    w("//! Static font metric data extracted from DejaVu TTF files.")
    w("//!")
    w("//! Auto-generated by gen_font_data.py — do not edit manually.")
    w("//!")
    w("//! This replaces runtime TTF parsing with pre-extracted static tables,")
    w("//! eliminating the need to embed 2.5 MB of TTF data and the ttf-parser dependency.")
    w("")
    w("/// Metadata for a single font face.")
    w("#[derive(Debug, Clone, Copy)]")
    w("pub struct FontMeta {")
    w("    pub units_per_em: u16,")
    w("    pub ascender: i16,")
    w("    pub descender: i16,")
    w("    pub typo_ascender: i16,")
    w("    /// Range table: sorted by start codepoint, (start, end, advance).")
    w("    /// Binary search on `start` to find the range containing a codepoint.")
    w("    ranges: &'static [(u32, u32, u16)],")
    w("}")
    w("")
    w("impl FontMeta {")
    w("    /// Look up the horizontal advance for a Unicode codepoint.")
    w("    /// Returns `None` if the codepoint has no glyph in this font.")
    w("    #[inline]")
    w("    pub fn glyph_advance(&self, codepoint: u32) -> Option<u16> {")
    w("        // Binary search for the range containing this codepoint")
    w("        let idx = self.ranges.partition_point(|&(start, _, _)| start <= codepoint);")
    w("        if idx == 0 {")
    w("            return None;")
    w("        }")
    w("        let (start, end, adv) = self.ranges[idx - 1];")
    w("        if codepoint >= start && codepoint <= end {")
    w("            Some(adv)")
    w("        } else {")
    w("            None")
    w("        }")
    w("    }")
    w("}")
    w("")

    for name, info in fonts_data:
        ranges = info['ranges']
        w(f"pub static {name}: FontMeta = FontMeta {{")
        w(f"    units_per_em: {info['units_per_em']},")
        w(f"    ascender: {info['ascender']},")
        w(f"    descender: {info['descender']},")
        w(f"    typo_ascender: {info['typo_ascender']},")
        w(f"    ranges: &{name}_RANGES,")
        w(f"}};")
        w("")

        # Write range data
        w(f"/// {len(ranges)} ranges covering {info['num_codepoints']} codepoints.")
        w(f"static {name}_RANGES: [(u32, u32, u16); {len(ranges)}] = [")
        for start, end, adv in ranges:
            if start == end:
                w(f"    (0x{start:04X}, 0x{end:04X}, {adv}), // U+{start:04X}")
            else:
                w(f"    (0x{start:04X}, 0x{end:04X}, {adv}), // U+{start:04X}..U+{end:04X}")
        w("];")
        w("")

    return "\n".join(lines)


def main():
    fonts_data = []
    for name, path in FONTS:
        full_path = f"/ext/plantuml/plantuml-little/{path}"
        print(f"Extracting {name} from {path}...", file=sys.stderr)
        info = extract_font(full_path)
        print(f"  units_per_em={info['units_per_em']}, ascender={info['ascender']}, "
              f"descender={info['descender']}, typo_ascender={info['typo_ascender']}, "
              f"codepoints={info['num_codepoints']}, ranges={len(info['ranges'])}",
              file=sys.stderr)
        fonts_data.append((name, info))

    rust_code = generate_rust(fonts_data)

    out_path = "/ext/plantuml/plantuml-little/src/font_data.rs"
    with open(out_path, 'w') as f:
        f.write(rust_code)
        f.write("\n")
    print(f"Written to {out_path}", file=sys.stderr)

    # Print summary
    total_ranges = sum(len(info['ranges']) for _, info in fonts_data)
    total_cps = sum(info['num_codepoints'] for _, info in fonts_data)
    print(f"Total: {total_ranges} ranges, {total_cps} codepoints across {len(fonts_data)} fonts",
          file=sys.stderr)


if __name__ == '__main__':
    main()
