#!/usr/bin/env python3
"""Convert Java font metrics JSON to Rust source code.

Reads the JSON output from ExtractFontMetrics.java and generates
src/font_metrics.rs with const lookup tables.

Usage:
    python3 tests/tools/gen_metrics_table.py \
        tests/tools/font_metrics.json \
        > src/font_metrics.rs
"""

import json
import sys


def rust_char_literal(cp: int) -> str:
    """Convert a Unicode code point to a Rust char literal."""
    if cp == ord("'"):
        return "'\\''"
    elif cp == ord("\\"):
        return "'\\\\'"
    elif 0x20 <= cp <= 0x7E:
        return f"'{chr(cp)}'"
    else:
        return f"'\\u{{{cp:04X}}}'"


def char_from_json_key(key: str) -> int:
    """Parse a JSON key back to a code point."""
    if len(key) == 1:
        return ord(key)
    # Unicode escape: \uXXXX
    if key.startswith("\\u") or key.startswith("\\U"):
        return int(key[2:], 16)
    return ord(key)


def generate_table(data: dict, family: str, size: str, style: str) -> list:
    """Generate (char, width) pairs for a specific font config."""
    try:
        advances = data[family][size][style]["advances"]
    except KeyError:
        return []
    entries = []
    for key, width in advances.items():
        cp = char_from_json_key(key)
        entries.append((cp, width))
    entries.sort()
    return entries


def generate_vertical(data: dict, family: str, size: str, style: str) -> dict:
    """Get vertical metrics for a specific font config."""
    try:
        info = data[family][size][style]
        return {
            "ascent": info["ascent"],
            "descent": info["descent"],
            "leading": info["leading"],
            "height": info["height"],
        }
    except KeyError:
        return None


def main():
    if len(sys.argv) < 2:
        print("Usage: gen_metrics_table.py <font_metrics.json>", file=sys.stderr)
        sys.exit(1)

    with open(sys.argv[1]) as f:
        data = json.load(f)

    print("// Auto-generated by tests/tools/gen_metrics_table.py")
    print("// Do not edit manually. Regenerate with:")
    print("//   java -cp tests/tools ExtractFontMetrics > tests/tools/font_metrics.json")
    print("//   python3 tests/tools/gen_metrics_table.py tests/tools/font_metrics.json > src/font_metrics.rs")
    print()
    print("use std::collections::HashMap;")
    print("use std::sync::LazyLock;")
    print()

    # Collect all configurations we need
    configs = []
    for family in ["SansSerif", "Monospaced"]:
        for size in ["10", "11", "12", "13", "14", "17", "18"]:
            for style in ["plain", "bold", "italic", "bold_italic"]:
                entries = generate_table(data, family, size, style)
                vertical = generate_vertical(data, family, size, style)
                if entries and vertical:
                    configs.append((family, size, style, entries, vertical))

    # Generate a flat table for each config
    for family, size, style, entries, vertical in configs:
        table_name = f"ADV_{family.upper()}_{size}_{style.upper()}"
        print(f"const {table_name}: &[(char, f64)] = &[")
        for cp, width in entries:
            print(f"    ({rust_char_literal(cp)}, {width:.6f}),")
        print("];")
        print()

    # Generate vertical metrics tables
    print("struct VerticalMetrics {")
    print("    ascent: f64,")
    print("    descent: f64,")
    print("    #[allow(dead_code)]")
    print("    leading: f64,")
    print("    height: f64,")
    print("}")
    print()

    for family, size, style, _, vertical in configs:
        name = f"VERT_{family.upper()}_{size}_{style.upper()}"
        print(f"const {name}: VerticalMetrics = VerticalMetrics {{")
        print(f"    ascent: {vertical['ascent']:.6f},")
        print(f"    descent: {vertical['descent']:.6f},")
        print(f"    leading: {vertical['leading']:.6f},")
        print(f"    height: {vertical['height']:.6f},")
        print("};")
        print()

    # Generate the lookup infrastructure
    print("struct FontConfig {")
    print("    family: &'static str,")
    print("    size: u32,")
    print("    style: &'static str,")
    print("    advances: &'static [(char, f64)],")
    print("    vertical: &'static VerticalMetrics,")
    print("}")
    print()

    print("const ALL_CONFIGS: &[FontConfig] = &[")
    for family, size, style, _, _ in configs:
        adv_name = f"ADV_{family.upper()}_{size}_{style.upper()}"
        vert_name = f"VERT_{family.upper()}_{size}_{style.upper()}"
        print(f'    FontConfig {{ family: "{family}", size: {size}, style: "{style}", advances: {adv_name}, vertical: &{vert_name} }},')
    print("];")
    print()

    # Generate public API
    print("""
/// HashMap for O(1) character width lookup.
/// Key: (family, size, style, char) -> advance width
static ADVANCE_MAP: LazyLock<HashMap<(&'static str, u32, &'static str, char), f64>> = LazyLock::new(|| {
    let mut map = HashMap::new();
    for cfg in ALL_CONFIGS {
        for &(ch, width) in cfg.advances {
            map.insert((cfg.family, cfg.size, cfg.style, ch), width);
        }
    }
    map
});

fn style_name(bold: bool, italic: bool) -> &'static str {
    match (bold, italic) {
        (false, false) => "plain",
        (true, false) => "bold",
        (false, true) => "italic",
        (true, true) => "bold_italic",
    }
}

fn family_name(family: &str) -> &'static str {
    let lower = family.to_ascii_lowercase();
    if lower.contains("mono") || lower == "courier" || lower == "courier new" {
        "Monospaced"
    } else {
        "SansSerif"
    }
}

fn nearest_size(size: f64) -> u32 {
    const SIZES: [u32; 7] = [10, 11, 12, 13, 14, 17, 18];
    let target = size.round() as u32;
    *SIZES.iter().min_by_key(|&&s| (s as i32 - target as i32).unsigned_abs()).unwrap()
}

/// Get the advance width of a single character.
/// Falls back to a default width if the character is not in the table.
pub fn char_width(ch: char, family: &str, size: f64, bold: bool, italic: bool) -> f64 {
    let fam = family_name(family);
    let sz = nearest_size(size);
    let sty = style_name(bold, italic);

    if let Some(&w) = ADVANCE_MAP.get(&(fam, sz, sty, ch)) {
        // Scale if the requested size differs from the table size
        w * size / (sz as f64)
    } else {
        // Fallback: use space width as approximation
        let space_w = ADVANCE_MAP.get(&(fam, sz, sty, ' '))
            .copied()
            .unwrap_or(size * 0.6);
        space_w * size / (sz as f64)
    }
}

/// Measure the total advance width of a string.
pub fn text_width(text: &str, family: &str, size: f64, bold: bool, italic: bool) -> f64 {
    text.chars().map(|c| char_width(c, family, size, bold, italic)).sum()
}

fn get_vertical(family: &str, size: f64, bold: bool, italic: bool) -> Option<&'static VerticalMetrics> {
    let fam = family_name(family);
    let sz = nearest_size(size);
    let sty = style_name(bold, italic);
    ALL_CONFIGS.iter()
        .find(|c| c.family == fam && c.size == sz && c.style == sty)
        .map(|c| c.vertical)
}

/// Get the line height (ascent + descent + leading) for the given font.
pub fn line_height(family: &str, size: f64, bold: bool, italic: bool) -> f64 {
    if let Some(v) = get_vertical(family, size, bold, italic) {
        v.height * size / (nearest_size(size) as f64)
    } else {
        size * 1.2
    }
}

/// Get the font ascent (baseline to top).
pub fn ascent(family: &str, size: f64, bold: bool, italic: bool) -> f64 {
    if let Some(v) = get_vertical(family, size, bold, italic) {
        v.ascent * size / (nearest_size(size) as f64)
    } else {
        size * 0.8
    }
}

/// Get the font descent (baseline to bottom).
pub fn descent(family: &str, size: f64, bold: bool, italic: bool) -> f64 {
    if let Some(v) = get_vertical(family, size, bold, italic) {
        v.descent * size / (nearest_size(size) as f64)
    } else {
        size * 0.2
    }
}
""")

if __name__ == "__main__":
    main()
