#!/usr/bin/env python3
"""Generate golden_tests.rs from fixture files.

Scans tests/fixtures/ for .puml files and generates a Rust test file
with one test per fixture, using the golden_test! macro.

Usage:
    python3 tests/generate_test_list.py > tests/golden_tests.rs
"""

import os
import re
import sys

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")

def sanitize_name(path: str) -> str:
    """Convert a fixture path to a valid Rust test function name."""
    # Remove extension and fixtures/ prefix
    name = path.replace("/", "_").replace("-", "_").replace(".", "_")
    # Ensure it starts with a letter
    if name and name[0].isdigit():
        name = "n" + name
    # Remove any non-alphanumeric characters except underscore
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    # Collapse multiple underscores
    name = re.sub(r"_+", "_", name).strip("_")
    return name

def main():
    fixtures = []

    for root, _dirs, files in os.walk(FIXTURES_DIR):
        for f in sorted(files):
            if not f.endswith(".puml"):
                continue
            full = os.path.join(root, f)
            rel = os.path.relpath(full, os.path.join(FIXTURES_DIR, ".."))
            # rel is like "fixtures/class/xmi0002.puml"
            fixtures.append(rel)

    fixtures.sort()

    print("// Auto-generated by tests/generate_test_list.py")
    print("// Do not edit manually. Regenerate with:")
    print("//   python3 tests/generate_test_list.py > tests/golden_tests.rs")
    print()
    print("use std::fs;")
    print("use std::path::Path;")
    print()
    print("fn convert_fixture(path: &str) -> String {")
    print('    let source = fs::read_to_string(path)')
    print('        .unwrap_or_else(|e| panic!("cannot read {path}: {e}"));')
    print("    plantuml_little::convert_with_input_path(&source, Path::new(path))")
    print('        .unwrap_or_else(|e| panic!("convert {path} failed: {e}"))')
    print("}")
    print()
    print("fn load_golden(fixture_path: &str) -> Option<String> {")
    print('    let golden_path = fixture_path')
    print('        .replace("fixtures/", "golden/")')
    print('        .replace(".puml", ".svg");')
    print("    fs::read_to_string(&golden_path).ok()")
    print("}")
    print()
    print("fn find_first_diff(a: &str, b: &str) -> (usize, usize, String) {")
    print("    let mut line = 1;")
    print("    let mut col = 1;")
    print("    for (i, (ca, cb)) in a.chars().zip(b.chars()).enumerate() {")
    print("        if ca != cb {")
    print('            let context_a = &a[i.saturating_sub(40)..a.len().min(i + 40)];')
    print('            let context_b = &b[i.saturating_sub(40)..b.len().min(i + 40)];')
    print('            return (line, col, format!("expected: ...{}...\\nactual:   ...{}...", context_b, context_a));')
    print("        }")
    print("        if ca == '\\n' { line += 1; col = 1; } else { col += 1; }")
    print("    }")
    print("    let la = a.len();")
    print("    let lb = b.len();")
    print('    (line, col, format!("length differs: actual={la}, expected={lb}"))')
    print("}")
    print()
    print("fn assert_exact_match(actual: &str, golden: &str, path: &str) {")
    print("    if actual == golden { return; }")
    print("    let (line, col, ctx) = find_first_diff(actual, golden);")
    print('    panic!("{path}: output differs from golden at line {line} col {col}\\n{ctx}");')
    print("}")
    print()
    print("fn assert_no_raw_markup(svg: &str, path: &str) {")
    print('    let raw_patterns: &[(&str, &str)] = &[')
    print('        ("<$", "raw sprite reference <$...>"),')
    print('        ("<size:", "raw <size:N> markup"),')
    print('        ("<color:", "raw <color:X> markup"),')
    print('        ("<back:", "raw <back:X> markup"),')
    print('        ("<font:", "raw <font:X> markup"),')
    print("    ];")
    print('    let escaped_patterns: &[(&str, &str)] = &[')
    print('        ("&lt;size:", "escaped <size:N> markup"),')
    print('        ("&lt;color:", "escaped <color:X> markup"),')
    print('        ("&lt;back:", "escaped <back:X> markup"),')
    print('        ("&lt;font:", "escaped <font:X> markup"),')
    print('        ("&lt;$", "escaped sprite reference <$...>"),')
    print("    ];")
    print("    for (pat, desc) in raw_patterns {")
    print('        assert!(!svg.contains(pat), "{path}: {desc} in SVG output");')
    print("    }")
    print("    for (pat, desc) in escaped_patterns {")
    print('        assert!(!svg.contains(pat), "{path}: {desc} in SVG output");')
    print("    }")
    print("    for line in svg.lines() {")
    print("        if let Some(start) = line.find('>') {")
    print('            if let Some(end) = line.rfind("</text>") {')
    print("                let text_content = &line[start + 1..end];")
    print('                if text_content.contains("**") {')
    print('                    panic!("{path}: unprocessed Creole bold **...** in text: {text_content}");')
    print("                }")
    print("            }")
    print("        }")
    print("    }")
    print("}")
    print()
    print("macro_rules! golden_test {")
    print("    ($name:ident, $fixture:expr) => {")
    print("        #[test]")
    print("        fn $name() {")
    print('            let fixture = concat!("tests/", $fixture);')
    print("            let svg = convert_fixture(fixture);")
    print("            assert_no_raw_markup(&svg, fixture);")
    print("            if let Some(golden) = load_golden(fixture) {")
    print("                assert_exact_match(&svg, &golden, fixture);")
    print("            }")
    print("        }")
    print("    };")
    print("}")
    print()

    for rel in fixtures:
        name = sanitize_name(rel)
        # rel is like "fixtures/class/xmi0002.puml" - keep as-is for the macro
        print(f'golden_test!(golden_{name}, "{rel}");')

    print()
    print(f"// Total: {len(fixtures)} golden tests")

if __name__ == "__main__":
    main()
