// Auto-generated by tests/generate_test_list.py
// Do not edit manually. Regenerate with:
//   python3 tests/generate_test_list.py > tests/golden_tests.rs

use std::fs;
use std::path::Path;

fn convert_fixture(path: &str) -> String {
    let source = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("cannot read {path}: {e}"));
    plantuml_little::convert_with_input_path(&source, Path::new(path))
        .unwrap_or_else(|e| panic!("convert {path} failed: {e}"))
}

fn load_golden(fixture_path: &str) -> Option<String> {
    let golden_path = fixture_path
        .replace("fixtures/", "golden/")
        .replace(".puml", ".svg");
    fs::read_to_string(&golden_path).ok()
}

fn find_first_diff(a: &str, b: &str) -> (usize, usize, String) {
    let mut line = 1;
    let mut col = 1;
    for (i, (ca, cb)) in a.chars().zip(b.chars()).enumerate() {
        if ca != cb {
            let context_a = &a[i.saturating_sub(40)..a.len().min(i + 40)];
            let context_b = &b[i.saturating_sub(40)..b.len().min(i + 40)];
            return (line, col, format!("expected: ...{}...\nactual:   ...{}...", context_b, context_a));
        }
        if ca == '\n' { line += 1; col = 1; } else { col += 1; }
    }
    let la = a.len();
    let lb = b.len();
    (line, col, format!("length differs: actual={la}, expected={lb}"))
}

fn assert_exact_match(actual: &str, golden: &str, path: &str) {
    if actual == golden { return; }
    let (line, col, ctx) = find_first_diff(actual, golden);
    panic!("{path}: output differs from golden at line {line} col {col}\n{ctx}");
}

fn assert_no_raw_markup(svg: &str, path: &str) {
    let raw_patterns: &[(&str, &str)] = &[
        ("<$", "raw sprite reference <$...>"),
        ("<size:", "raw <size:N> markup"),
        ("<color:", "raw <color:X> markup"),
        ("<back:", "raw <back:X> markup"),
        ("<font:", "raw <font:X> markup"),
    ];
    let escaped_patterns: &[(&str, &str)] = &[
        ("&lt;size:", "escaped <size:N> markup"),
        ("&lt;color:", "escaped <color:X> markup"),
        ("&lt;back:", "escaped <back:X> markup"),
        ("&lt;font:", "escaped <font:X> markup"),
        ("&lt;$", "escaped sprite reference <$...>"),
    ];
    for (pat, desc) in raw_patterns {
        assert!(!svg.contains(pat), "{path}: {desc} in SVG output");
    }
    for (pat, desc) in escaped_patterns {
        assert!(!svg.contains(pat), "{path}: {desc} in SVG output");
    }
    for line in svg.lines() {
        if let Some(start) = line.find('>') {
            if let Some(end) = line.rfind("</text>") {
                let text_content = &line[start + 1..end];
                if text_content.contains("**") {
                    panic!("{path}: unprocessed Creole bold **...** in text: {text_content}");
                }
            }
        }
    }
}

macro_rules! golden_test {
    ($name:ident, $fixture:expr) => {
        #[test]
        fn $name() {
            let fixture = concat!("tests/", $fixture);
            let svg = convert_fixture(fixture);
            assert_no_raw_markup(&svg, fixture);
            if let Some(golden) = load_golden(fixture) {
                assert_exact_match(&svg, &golden, fixture);
            }
        }
    };
}

golden_test!(golden_fixtures_activity_a0002_puml, "fixtures/activity/a0002.puml");
golden_test!(golden_fixtures_activity_activity_creole_table_01_puml, "fixtures/activity/activity_creole_table_01.puml");
golden_test!(golden_fixtures_activity_activity_creole_table_02_puml, "fixtures/activity/activity_creole_table_02.puml");
golden_test!(golden_fixtures_activity_activity_mono_multi_line_puml, "fixtures/activity/activity_mono_multi_line.puml");
golden_test!(golden_fixtures_activity_activity_mono_multi_line2_puml, "fixtures/activity/activity_mono_multi_line2.puml");
golden_test!(golden_fixtures_activity_activity_mono_multi_line2_v2_puml, "fixtures/activity/activity_mono_multi_line2_v2.puml");
golden_test!(golden_fixtures_activity_activity_mono_multi_line_v2_puml, "fixtures/activity/activity_mono_multi_line_v2.puml");
golden_test!(golden_fixtures_activity_swimlane001_puml, "fixtures/activity/swimlane001.puml");
golden_test!(golden_fixtures_class_a0005_puml, "fixtures/class/a0005.puml");
golden_test!(golden_fixtures_class_class_funcparam_arrow_01_puml, "fixtures/class/class_funcparam_arrow_01.puml");
golden_test!(golden_fixtures_class_class_funcparam_arrow_02_puml, "fixtures/class/class_funcparam_arrow_02.puml");
golden_test!(golden_fixtures_class_colors001_puml, "fixtures/class/colors001.puml");
golden_test!(golden_fixtures_class_generics001_puml, "fixtures/class/generics001.puml");
golden_test!(golden_fixtures_class_hideshow001_puml, "fixtures/class/hideshow001.puml");
golden_test!(golden_fixtures_class_hideshow002_puml, "fixtures/class/hideshow002.puml");
golden_test!(golden_fixtures_class_hideshow003_puml, "fixtures/class/hideshow003.puml");
golden_test!(golden_fixtures_class_hideshow004_puml, "fixtures/class/hideshow004.puml");
golden_test!(golden_fixtures_class_qualifiedassoc001_puml, "fixtures/class/qualifiedassoc001.puml");
golden_test!(golden_fixtures_class_qualifiedassoc002_puml, "fixtures/class/qualifiedassoc002.puml");
golden_test!(golden_fixtures_class_xmi0002_puml, "fixtures/class/xmi0002.puml");
golden_test!(golden_fixtures_class_xmi0003_puml, "fixtures/class/xmi0003.puml");
golden_test!(golden_fixtures_class_xmi0004_puml, "fixtures/class/xmi0004.puml");
golden_test!(golden_fixtures_component_buitin_newline_chr_puml, "fixtures/component/buitin_newline_chr.puml");
golden_test!(golden_fixtures_component_colors001_puml, "fixtures/component/colors001.puml");
golden_test!(golden_fixtures_component_componentextraarrows_0001_puml, "fixtures/component/componentextraarrows_0001.puml");
golden_test!(golden_fixtures_component_deployment01_puml, "fixtures/component/deployment01.puml");
golden_test!(golden_fixtures_component_deployment_last_name_multi_line_puml, "fixtures/component/deployment_last_name_multi_line.puml");
golden_test!(golden_fixtures_component_gml0000_puml, "fixtures/component/gml0000.puml");
golden_test!(golden_fixtures_component_gml0001_puml, "fixtures/component/gml0001.puml");
golden_test!(golden_fixtures_component_jaws5_puml, "fixtures/component/jaws5.puml");
golden_test!(golden_fixtures_component_subdiagram_theme_02_puml, "fixtures/component/subdiagram_theme_02.puml");
golden_test!(golden_fixtures_component_xmi0001_puml, "fixtures/component/xmi0001.puml");
golden_test!(golden_fixtures_dev_jaws_jaws1_puml, "fixtures/dev/jaws/jaws1.puml");
golden_test!(golden_fixtures_dev_jaws_jaws10_puml, "fixtures/dev/jaws/jaws10.puml");
golden_test!(golden_fixtures_dev_jaws_jaws11_puml, "fixtures/dev/jaws/jaws11.puml");
golden_test!(golden_fixtures_dev_jaws_jaws12_puml, "fixtures/dev/jaws/jaws12.puml");
golden_test!(golden_fixtures_dev_jaws_jaws2_puml, "fixtures/dev/jaws/jaws2.puml");
golden_test!(golden_fixtures_dev_jaws_jaws3_puml, "fixtures/dev/jaws/jaws3.puml");
golden_test!(golden_fixtures_dev_jaws_jaws4_puml, "fixtures/dev/jaws/jaws4.puml");
golden_test!(golden_fixtures_dev_jaws_jaws5_puml, "fixtures/dev/jaws/jaws5.puml");
golden_test!(golden_fixtures_dev_jaws_jaws6_puml, "fixtures/dev/jaws/jaws6.puml");
golden_test!(golden_fixtures_dev_jaws_jaws7_puml, "fixtures/dev/jaws/jaws7.puml");
golden_test!(golden_fixtures_dev_jaws_jaws8_puml, "fixtures/dev/jaws/jaws8.puml");
golden_test!(golden_fixtures_dev_jaws_jaws9_puml, "fixtures/dev/jaws/jaws9.puml");
golden_test!(golden_fixtures_dev_newline_WBS_arrow_puml, "fixtures/dev/newline/WBS_arrow.puml");
golden_test!(golden_fixtures_dev_newline_WBS_direction_puml, "fixtures/dev/newline/WBS_direction.puml");
golden_test!(golden_fixtures_dev_newline_activity_creole_table_puml, "fixtures/dev/newline/activity_creole_table.puml");
golden_test!(golden_fixtures_dev_newline_activity_mono_multi_line_puml, "fixtures/dev/newline/activity_mono_multi_line.puml");
golden_test!(golden_fixtures_dev_newline_activity_mono_multi_line2_puml, "fixtures/dev/newline/activity_mono_multi_line2.puml");
golden_test!(golden_fixtures_dev_newline_builtin_newline_puml, "fixtures/dev/newline/builtin_newline.puml");
golden_test!(golden_fixtures_dev_newline_buitin_newline_chr_puml, "fixtures/dev/newline/buitin_newline_chr.puml");
golden_test!(golden_fixtures_dev_newline_class_funcparam_arrow_puml, "fixtures/dev/newline/class_funcparam_arrow.puml");
golden_test!(golden_fixtures_dev_newline_deployment_last_name_multi_line_puml, "fixtures/dev/newline/deployment_last_name_multi_line.puml");
golden_test!(golden_fixtures_dev_newline_deployment_mono_multi_line_puml, "fixtures/dev/newline/deployment_mono_multi_line.puml");
golden_test!(golden_fixtures_dev_newline_deployment_on_name_puml, "fixtures/dev/newline/deployment_on_name.puml");
golden_test!(golden_fixtures_dev_newline_json_escaped_puml, "fixtures/dev/newline/json_escaped.puml");
golden_test!(golden_fixtures_dev_newline_link_URL_tooltip_puml, "fixtures/dev/newline/link_URL_tooltip.puml");
golden_test!(golden_fixtures_dev_newline_preproc_functionparam_line_continuation_puml, "fixtures/dev/newline/preproc_functionparam_line_continuation.puml");
golden_test!(golden_fixtures_dev_newline_seq_mono_line_puml, "fixtures/dev/newline/seq_mono_line.puml");
golden_test!(golden_fixtures_dev_newline_state_monoline_puml, "fixtures/dev/newline/state_monoline.puml");
golden_test!(golden_fixtures_dev_newline_subdiagram_theme_puml, "fixtures/dev/newline/subdiagram_theme.puml");
golden_test!(golden_fixtures_dev_newlinev2_activity_mono_multi_line2_v2_puml, "fixtures/dev/newlinev2/activity_mono_multi_line2_v2.puml");
golden_test!(golden_fixtures_dev_newlinev2_activity_mono_multi_line_v2_puml, "fixtures/dev/newlinev2/activity_mono_multi_line_v2.puml");
golden_test!(golden_fixtures_ditaa_basic_puml, "fixtures/ditaa/basic.puml");
golden_test!(golden_fixtures_dot_basic_puml, "fixtures/dot/basic.puml");
golden_test!(golden_fixtures_erd_chenmovie_puml, "fixtures/erd/chenmovie.puml");
golden_test!(golden_fixtures_erd_chenmoviealias_puml, "fixtures/erd/chenmoviealias.puml");
golden_test!(golden_fixtures_erd_chenmovieextended_puml, "fixtures/erd/chenmovieextended.puml");
golden_test!(golden_fixtures_erd_chenrankdir_puml, "fixtures/erd/chenrankdir.puml");
golden_test!(golden_fixtures_erd_weak001_puml, "fixtures/erd/weak001.puml");
golden_test!(golden_fixtures_gantt_a0003_puml, "fixtures/gantt/a0003.puml");
golden_test!(golden_fixtures_json_json_escaped_puml, "fixtures/json/json_escaped.puml");
golden_test!(golden_fixtures_mindmap_jaws12_puml, "fixtures/mindmap/jaws12.puml");
golden_test!(golden_fixtures_misc_a0004_puml, "fixtures/misc/a0004.puml");
golden_test!(golden_fixtures_misc_creole_back001_puml, "fixtures/misc/creole_back001.puml");
golden_test!(golden_fixtures_misc_creole_font001_puml, "fixtures/misc/creole_font001.puml");
golden_test!(golden_fixtures_misc_creole_mixed001_puml, "fixtures/misc/creole_mixed001.puml");
golden_test!(golden_fixtures_misc_creole_note001_puml, "fixtures/misc/creole_note001.puml");
golden_test!(golden_fixtures_misc_creole_sup_sub001_puml, "fixtures/misc/creole_sup_sub001.puml");
golden_test!(golden_fixtures_misc_deployment_on_name_puml, "fixtures/misc/deployment_on_name.puml");
golden_test!(golden_fixtures_misc_link_url_tooltip_04_puml, "fixtures/misc/link_url_tooltip_04.puml");
golden_test!(golden_fixtures_misc_link_url_tooltip_05_puml, "fixtures/misc/link_url_tooltip_05.puml");
golden_test!(golden_fixtures_misc_meta_title_header_footer_puml, "fixtures/misc/meta_title_header_footer.puml");
golden_test!(golden_fixtures_misc_skinparam_class001_puml, "fixtures/misc/skinparam_class001.puml");
golden_test!(golden_fixtures_misc_skinparam_colors001_puml, "fixtures/misc/skinparam_colors001.puml");
golden_test!(golden_fixtures_misc_skinparam_font001_puml, "fixtures/misc/skinparam_font001.puml");
golden_test!(golden_fixtures_misc_skinparam_handwritten001_puml, "fixtures/misc/skinparam_handwritten001.puml");
golden_test!(golden_fixtures_misc_skinparam_monochrome001_puml, "fixtures/misc/skinparam_monochrome001.puml");
golden_test!(golden_fixtures_misc_skinparam_roundcorner001_puml, "fixtures/misc/skinparam_roundcorner001.puml");
golden_test!(golden_fixtures_misc_skinparam_sequence001_puml, "fixtures/misc/skinparam_sequence001.puml");
golden_test!(golden_fixtures_misc_xmi0000_puml, "fixtures/misc/xmi0000.puml");
golden_test!(golden_fixtures_nonreg_graphml_GML0000_puml, "fixtures/nonreg/graphml/GML0000.puml");
golden_test!(golden_fixtures_nonreg_graphml_GML0001_puml, "fixtures/nonreg/graphml/GML0001.puml");
golden_test!(golden_fixtures_nonreg_scxml_SCXML0001_puml, "fixtures/nonreg/scxml/SCXML0001.puml");
golden_test!(golden_fixtures_nonreg_scxml_SCXML0002_puml, "fixtures/nonreg/scxml/SCXML0002.puml");
golden_test!(golden_fixtures_nonreg_scxml_SCXML0003_puml, "fixtures/nonreg/scxml/SCXML0003.puml");
golden_test!(golden_fixtures_nonreg_scxml_SCXML0004_puml, "fixtures/nonreg/scxml/SCXML0004.puml");
golden_test!(golden_fixtures_nonreg_scxml_SCXML0005_puml, "fixtures/nonreg/scxml/SCXML0005.puml");
golden_test!(golden_fixtures_nonreg_simple_A0000_puml, "fixtures/nonreg/simple/A0000.puml");
golden_test!(golden_fixtures_nonreg_simple_A0001_puml, "fixtures/nonreg/simple/A0001.puml");
golden_test!(golden_fixtures_nonreg_simple_A0002_puml, "fixtures/nonreg/simple/A0002.puml");
golden_test!(golden_fixtures_nonreg_simple_A0003_puml, "fixtures/nonreg/simple/A0003.puml");
golden_test!(golden_fixtures_nonreg_simple_A0004_puml, "fixtures/nonreg/simple/A0004.puml");
golden_test!(golden_fixtures_nonreg_simple_A0005_puml, "fixtures/nonreg/simple/A0005.puml");
golden_test!(golden_fixtures_nonreg_simple_A0006_puml, "fixtures/nonreg/simple/A0006.puml");
golden_test!(golden_fixtures_nonreg_simple_ChenMovie_puml, "fixtures/nonreg/simple/ChenMovie.puml");
golden_test!(golden_fixtures_nonreg_simple_ChenMovieAlias_puml, "fixtures/nonreg/simple/ChenMovieAlias.puml");
golden_test!(golden_fixtures_nonreg_simple_ChenMovieExtended_puml, "fixtures/nonreg/simple/ChenMovieExtended.puml");
golden_test!(golden_fixtures_nonreg_simple_ChenRankDir_puml, "fixtures/nonreg/simple/ChenRankDir.puml");
golden_test!(golden_fixtures_nonreg_simple_ComponentExtraArrows_0001_puml, "fixtures/nonreg/simple/ComponentExtraArrows_0001.puml");
golden_test!(golden_fixtures_nonreg_simple_HideShow001_puml, "fixtures/nonreg/simple/HideShow001.puml");
golden_test!(golden_fixtures_nonreg_simple_HideShow002_puml, "fixtures/nonreg/simple/HideShow002.puml");
golden_test!(golden_fixtures_nonreg_simple_HideShow003_puml, "fixtures/nonreg/simple/HideShow003.puml");
golden_test!(golden_fixtures_nonreg_simple_HideShow004_puml, "fixtures/nonreg/simple/HideShow004.puml");
golden_test!(golden_fixtures_nonreg_simple_QualifiedAssoc001_puml, "fixtures/nonreg/simple/QualifiedAssoc001.puml");
golden_test!(golden_fixtures_nonreg_simple_QualifiedAssoc002_puml, "fixtures/nonreg/simple/QualifiedAssoc002.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceArrows_0001_puml, "fixtures/nonreg/simple/SequenceArrows_0001.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceArrows_0002_puml, "fixtures/nonreg/simple/SequenceArrows_0002.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLayout_0001_puml, "fixtures/nonreg/simple/SequenceLayout_0001.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLayout_0001b_puml, "fixtures/nonreg/simple/SequenceLayout_0001b.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLayout_0001c_puml, "fixtures/nonreg/simple/SequenceLayout_0001c.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLayout_0002_puml, "fixtures/nonreg/simple/SequenceLayout_0002.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLayout_0003_puml, "fixtures/nonreg/simple/SequenceLayout_0003.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLayout_0004_puml, "fixtures/nonreg/simple/SequenceLayout_0004.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLayout_0005_puml, "fixtures/nonreg/simple/SequenceLayout_0005.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLayout_0005b_puml, "fixtures/nonreg/simple/SequenceLayout_0005b.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLayout_0006_puml, "fixtures/nonreg/simple/SequenceLayout_0006.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLeftMessageAndActiveLifeLines_0001_puml, "fixtures/nonreg/simple/SequenceLeftMessageAndActiveLifeLines_0001.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLeftMessageAndActiveLifeLines_0002_puml, "fixtures/nonreg/simple/SequenceLeftMessageAndActiveLifeLines_0002.puml");
golden_test!(golden_fixtures_nonreg_simple_SequenceLeftMessageAndActiveLifeLines_0003_puml, "fixtures/nonreg/simple/SequenceLeftMessageAndActiveLifeLines_0003.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozAltElseParallel_0001_puml, "fixtures/nonreg/simple/TeozAltElseParallel_0001.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozAltElseParallel_0002_puml, "fixtures/nonreg/simple/TeozAltElseParallel_0002.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozAltElseParallel_0003_puml, "fixtures/nonreg/simple/TeozAltElseParallel_0003.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozAltElseParallel_0004_puml, "fixtures/nonreg/simple/TeozAltElseParallel_0004.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozAltElseParallel_0005_puml, "fixtures/nonreg/simple/TeozAltElseParallel_0005.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozAltElseParallel_0006_puml, "fixtures/nonreg/simple/TeozAltElseParallel_0006.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozTimelineIssues_0001_puml, "fixtures/nonreg/simple/TeozTimelineIssues_0001.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozTimelineIssues_0002_puml, "fixtures/nonreg/simple/TeozTimelineIssues_0002.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozTimelineIssues_0003_puml, "fixtures/nonreg/simple/TeozTimelineIssues_0003.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozTimelineIssues_0004_puml, "fixtures/nonreg/simple/TeozTimelineIssues_0004.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozTimelineIssues_0005_puml, "fixtures/nonreg/simple/TeozTimelineIssues_0005.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozTimelineIssues_0006_puml, "fixtures/nonreg/simple/TeozTimelineIssues_0006.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozTimelineIssues_0007_puml, "fixtures/nonreg/simple/TeozTimelineIssues_0007.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozTimelineIssues_0008_puml, "fixtures/nonreg/simple/TeozTimelineIssues_0008.puml");
golden_test!(golden_fixtures_nonreg_simple_TeozTimelineIssues_0009_puml, "fixtures/nonreg/simple/TeozTimelineIssues_0009.puml");
golden_test!(golden_fixtures_nonreg_simple_TimingMessageArrowFont_0001_puml, "fixtures/nonreg/simple/TimingMessageArrowFont_0001.puml");
golden_test!(golden_fixtures_nonreg_simple_TimingMessageArrowFont_0002_puml, "fixtures/nonreg/simple/TimingMessageArrowFont_0002.puml");
golden_test!(golden_fixtures_nonreg_svg_SVG0001_puml, "fixtures/nonreg/svg/SVG0001.puml");
golden_test!(golden_fixtures_nonreg_svg_SVG0002_puml, "fixtures/nonreg/svg/SVG0002.puml");
golden_test!(golden_fixtures_nonreg_svg_SVG0003_puml, "fixtures/nonreg/svg/SVG0003.puml");
golden_test!(golden_fixtures_nonreg_svg_SVG0004_Smetana_puml, "fixtures/nonreg/svg/SVG0004_Smetana.puml");
golden_test!(golden_fixtures_nonreg_svg_SVG0004_Svek_puml, "fixtures/nonreg/svg/SVG0004_Svek.puml");
golden_test!(golden_fixtures_nonreg_svg_SVG0005_Smetana_puml, "fixtures/nonreg/svg/SVG0005_Smetana.puml");
golden_test!(golden_fixtures_nonreg_svg_SVG0005_Svek_puml, "fixtures/nonreg/svg/SVG0005_Svek.puml");
golden_test!(golden_fixtures_nonreg_svg_SVG0006_Svek_puml, "fixtures/nonreg/svg/SVG0006_Svek.puml");
golden_test!(golden_fixtures_nonreg_xmi_clazz_XMI0000_puml, "fixtures/nonreg/xmi/clazz/XMI0000.puml");
golden_test!(golden_fixtures_nonreg_xmi_clazz_XMI0002_puml, "fixtures/nonreg/xmi/clazz/XMI0002.puml");
golden_test!(golden_fixtures_nonreg_xmi_clazz_XMI0003_puml, "fixtures/nonreg/xmi/clazz/XMI0003.puml");
golden_test!(golden_fixtures_nonreg_xmi_clazz_XMI0004_puml, "fixtures/nonreg/xmi/clazz/XMI0004.puml");
golden_test!(golden_fixtures_nonreg_xmi_component_XMI0001_puml, "fixtures/nonreg/xmi/component/XMI0001.puml");
golden_test!(golden_fixtures_nwdiag_basic_puml, "fixtures/nwdiag/basic.puml");
golden_test!(golden_fixtures_object_basic_puml, "fixtures/object/basic.puml");
golden_test!(golden_fixtures_preprocessor_builtin_newline_puml, "fixtures/preprocessor/builtin_newline.puml");
golden_test!(golden_fixtures_preprocessor_deployment_mono_multi_line_puml, "fixtures/preprocessor/deployment_mono_multi_line.puml");
golden_test!(golden_fixtures_preprocessor_jaws1_puml, "fixtures/preprocessor/jaws1.puml");
golden_test!(golden_fixtures_preprocessor_jaws3_puml, "fixtures/preprocessor/jaws3.puml");
golden_test!(golden_fixtures_preprocessor_jaws6_puml, "fixtures/preprocessor/jaws6.puml");
golden_test!(golden_fixtures_preprocessor_jaws7_puml, "fixtures/preprocessor/jaws7.puml");
golden_test!(golden_fixtures_preprocessor_jaws8_puml, "fixtures/preprocessor/jaws8.puml");
golden_test!(golden_fixtures_preprocessor_jaws9_puml, "fixtures/preprocessor/jaws9.puml");
golden_test!(golden_fixtures_preprocessor_preproc_functionparam_line_continuation_puml, "fixtures/preprocessor/preproc_functionparam_line_continuation.puml");
golden_test!(golden_fixtures_preprocessor_seq_mono_line_puml, "fixtures/preprocessor/seq_mono_line.puml");
golden_test!(golden_fixtures_preprocessor_sequencearrows_0001_puml, "fixtures/preprocessor/sequencearrows_0001.puml");
golden_test!(golden_fixtures_preprocessor_sequencearrows_0002_puml, "fixtures/preprocessor/sequencearrows_0002.puml");
golden_test!(golden_fixtures_preprocessor_sequencelayout_0004_puml, "fixtures/preprocessor/sequencelayout_0004.puml");
golden_test!(golden_fixtures_preprocessor_sequencelayout_0005_puml, "fixtures/preprocessor/sequencelayout_0005.puml");
golden_test!(golden_fixtures_preprocessor_sequencelayout_0005b_puml, "fixtures/preprocessor/sequencelayout_0005b.puml");
golden_test!(golden_fixtures_preprocessor_sequenceleftmessageandactivelifelines_0001_puml, "fixtures/preprocessor/sequenceleftmessageandactivelifelines_0001.puml");
golden_test!(golden_fixtures_preprocessor_subdiagram_theme_01_puml, "fixtures/preprocessor/subdiagram_theme_01.puml");
golden_test!(golden_fixtures_preprocessor_svg0002_puml, "fixtures/preprocessor/svg0002.puml");
golden_test!(golden_fixtures_preprocessor_svg0004_smetana_puml, "fixtures/preprocessor/svg0004_smetana.puml");
golden_test!(golden_fixtures_preprocessor_svg0004_svek_puml, "fixtures/preprocessor/svg0004_svek.puml");
golden_test!(golden_fixtures_preprocessor_svg0005_smetana_puml, "fixtures/preprocessor/svg0005_smetana.puml");
golden_test!(golden_fixtures_preprocessor_svg0005_svek_puml, "fixtures/preprocessor/svg0005_svek.puml");
golden_test!(golden_fixtures_preprocessor_svg0006_svek_puml, "fixtures/preprocessor/svg0006_svek.puml");
golden_test!(golden_fixtures_preprocessor_teozaltelseparallel_0001_puml, "fixtures/preprocessor/teozaltelseparallel_0001.puml");
golden_test!(golden_fixtures_preprocessor_teozaltelseparallel_0002_puml, "fixtures/preprocessor/teozaltelseparallel_0002.puml");
golden_test!(golden_fixtures_preprocessor_teozaltelseparallel_0003_puml, "fixtures/preprocessor/teozaltelseparallel_0003.puml");
golden_test!(golden_fixtures_preprocessor_teozaltelseparallel_0004_puml, "fixtures/preprocessor/teozaltelseparallel_0004.puml");
golden_test!(golden_fixtures_preprocessor_teozaltelseparallel_0005_puml, "fixtures/preprocessor/teozaltelseparallel_0005.puml");
golden_test!(golden_fixtures_preprocessor_teozaltelseparallel_0006_puml, "fixtures/preprocessor/teozaltelseparallel_0006.puml");
golden_test!(golden_fixtures_preprocessor_teoztimelineissues_0001_puml, "fixtures/preprocessor/teoztimelineissues_0001.puml");
golden_test!(golden_fixtures_preprocessor_teoztimelineissues_0002_puml, "fixtures/preprocessor/teoztimelineissues_0002.puml");
golden_test!(golden_fixtures_preprocessor_teoztimelineissues_0003_puml, "fixtures/preprocessor/teoztimelineissues_0003.puml");
golden_test!(golden_fixtures_preprocessor_teoztimelineissues_0004_puml, "fixtures/preprocessor/teoztimelineissues_0004.puml");
golden_test!(golden_fixtures_preprocessor_teoztimelineissues_0005_puml, "fixtures/preprocessor/teoztimelineissues_0005.puml");
golden_test!(golden_fixtures_preprocessor_teoztimelineissues_0006_puml, "fixtures/preprocessor/teoztimelineissues_0006.puml");
golden_test!(golden_fixtures_preprocessor_teoztimelineissues_0007_puml, "fixtures/preprocessor/teoztimelineissues_0007.puml");
golden_test!(golden_fixtures_preprocessor_teoztimelineissues_0008_puml, "fixtures/preprocessor/teoztimelineissues_0008.puml");
golden_test!(golden_fixtures_preprocessor_teoztimelineissues_0009_puml, "fixtures/preprocessor/teoztimelineissues_0009.puml");
golden_test!(golden_fixtures_salt_basic_puml, "fixtures/salt/basic.puml");
golden_test!(golden_fixtures_sequence_a0000_puml, "fixtures/sequence/a0000.puml");
golden_test!(golden_fixtures_sequence_a0001_puml, "fixtures/sequence/a0001.puml");
golden_test!(golden_fixtures_sequence_a0006_puml, "fixtures/sequence/a0006.puml");
golden_test!(golden_fixtures_sequence_intermediatetest_0000_puml, "fixtures/sequence/intermediatetest_0000.puml");
golden_test!(golden_fixtures_sequence_jaws10_puml, "fixtures/sequence/jaws10.puml");
golden_test!(golden_fixtures_sequence_jaws11_puml, "fixtures/sequence/jaws11.puml");
golden_test!(golden_fixtures_sequence_jaws2_puml, "fixtures/sequence/jaws2.puml");
golden_test!(golden_fixtures_sequence_jaws4_puml, "fixtures/sequence/jaws4.puml");
golden_test!(golden_fixtures_sequence_seq_alt001_puml, "fixtures/sequence/seq_alt001.puml");
golden_test!(golden_fixtures_sequence_seq_autonumber001_puml, "fixtures/sequence/seq_autonumber001.puml");
golden_test!(golden_fixtures_sequence_seq_break001_puml, "fixtures/sequence/seq_break001.puml");
golden_test!(golden_fixtures_sequence_seq_critical001_puml, "fixtures/sequence/seq_critical001.puml");
golden_test!(golden_fixtures_sequence_seq_divider001_puml, "fixtures/sequence/seq_divider001.puml");
golden_test!(golden_fixtures_sequence_seq_group001_puml, "fixtures/sequence/seq_group001.puml");
golden_test!(golden_fixtures_sequence_seq_loop001_puml, "fixtures/sequence/seq_loop001.puml");
golden_test!(golden_fixtures_sequence_seq_nested001_puml, "fixtures/sequence/seq_nested001.puml");
golden_test!(golden_fixtures_sequence_seq_opt001_puml, "fixtures/sequence/seq_opt001.puml");
golden_test!(golden_fixtures_sequence_seq_par001_puml, "fixtures/sequence/seq_par001.puml");
golden_test!(golden_fixtures_sequence_seq_participants001_puml, "fixtures/sequence/seq_participants001.puml");
golden_test!(golden_fixtures_sequence_seq_ref001_puml, "fixtures/sequence/seq_ref001.puml");
golden_test!(golden_fixtures_sequence_sequencelayout_0001_puml, "fixtures/sequence/sequencelayout_0001.puml");
golden_test!(golden_fixtures_sequence_sequencelayout_0001b_puml, "fixtures/sequence/sequencelayout_0001b.puml");
golden_test!(golden_fixtures_sequence_sequencelayout_0001c_puml, "fixtures/sequence/sequencelayout_0001c.puml");
golden_test!(golden_fixtures_sequence_sequencelayout_0002_puml, "fixtures/sequence/sequencelayout_0002.puml");
golden_test!(golden_fixtures_sequence_sequencelayout_0003_puml, "fixtures/sequence/sequencelayout_0003.puml");
golden_test!(golden_fixtures_sequence_sequencelayout_0006_puml, "fixtures/sequence/sequencelayout_0006.puml");
golden_test!(golden_fixtures_sequence_sequenceleftmessageandactivelifelines_0002_puml, "fixtures/sequence/sequenceleftmessageandactivelifelines_0002.puml");
golden_test!(golden_fixtures_sequence_sequenceleftmessageandactivelifelines_0003_puml, "fixtures/sequence/sequenceleftmessageandactivelifelines_0003.puml");
golden_test!(golden_fixtures_sequence_svg0001_puml, "fixtures/sequence/svg0001.puml");
golden_test!(golden_fixtures_sequence_svg0003_puml, "fixtures/sequence/svg0003.puml");
golden_test!(golden_fixtures_sequence_test_0_puml, "fixtures/sequence/test_0.puml");
golden_test!(golden_fixtures_sprite_azureSVG_puml, "fixtures/sprite/azureSVG.puml");
golden_test!(golden_fixtures_sprite_linearGradientSpreadPad_puml, "fixtures/sprite/linearGradientSpreadPad.puml");
golden_test!(golden_fixtures_sprite_linearGradientSpreadReflect_puml, "fixtures/sprite/linearGradientSpreadReflect.puml");
golden_test!(golden_fixtures_sprite_linearGradientSpreadRepeat_puml, "fixtures/sprite/linearGradientSpreadRepeat.puml");
golden_test!(golden_fixtures_sprite_styleFontWeightRoboto_puml, "fixtures/sprite/styleFontWeightRoboto.puml");
golden_test!(golden_fixtures_sprite_svg2Groups_puml, "fixtures/sprite/svg2Groups.puml");
golden_test!(golden_fixtures_sprite_svg2GroupsInlineStyled_puml, "fixtures/sprite/svg2GroupsInlineStyled.puml");
golden_test!(golden_fixtures_sprite_svg2GroupsWithStyle_puml, "fixtures/sprite/svg2GroupsWithStyle.puml");
golden_test!(golden_fixtures_sprite_svgDiagonalGradientBLTR_puml, "fixtures/sprite/svgDiagonalGradientBLTR.puml");
golden_test!(golden_fixtures_sprite_svgDiagonalGradientBLTRMonochrome_puml, "fixtures/sprite/svgDiagonalGradientBLTRMonochrome.puml");
golden_test!(golden_fixtures_sprite_svgDiagonalGradientTLBR_puml, "fixtures/sprite/svgDiagonalGradientTLBR.puml");
golden_test!(golden_fixtures_sprite_svgEmbeddedPNG_puml, "fixtures/sprite/svgEmbeddedPNG.puml");
golden_test!(golden_fixtures_sprite_svgFillColourTest_2174_puml, "fixtures/sprite/svgFillColourTest_2174.puml");
golden_test!(golden_fixtures_sprite_svgFontWeightMultiWeight_puml, "fixtures/sprite/svgFontWeightMultiWeight.puml");
golden_test!(golden_fixtures_sprite_svgFontWeightStandardFonts_puml, "fixtures/sprite/svgFontWeightStandardFonts.puml");
golden_test!(golden_fixtures_sprite_svgLinearGradientCircle_puml, "fixtures/sprite/svgLinearGradientCircle.puml");
golden_test!(golden_fixtures_sprite_svgPolygonStar_puml, "fixtures/sprite/svgPolygonStar.puml");
golden_test!(golden_fixtures_sprite_svgRadialGradient_puml, "fixtures/sprite/svgRadialGradient.puml");
golden_test!(golden_fixtures_sprite_svgRedCircle_puml, "fixtures/sprite/svgRedCircle.puml");
golden_test!(golden_fixtures_sprite_svgRedEllipse_puml, "fixtures/sprite/svgRedEllipse.puml");
golden_test!(golden_fixtures_sprite_svgRedLine_puml, "fixtures/sprite/svgRedLine.puml");
golden_test!(golden_fixtures_sprite_svgRedPolyLine_puml, "fixtures/sprite/svgRedPolyLine.puml");
golden_test!(golden_fixtures_sprite_svgRedRect_puml, "fixtures/sprite/svgRedRect.puml");
golden_test!(golden_fixtures_sprite_svgRedRectLinearGradient_puml, "fixtures/sprite/svgRedRectLinearGradient.puml");
golden_test!(golden_fixtures_sprite_svgRedStroke_puml, "fixtures/sprite/svgRedStroke.puml");
golden_test!(golden_fixtures_sprite_svgRedText_puml, "fixtures/sprite/svgRedText.puml");
golden_test!(golden_fixtures_sprite_svgTextAnchor_puml, "fixtures/sprite/svgTextAnchor.puml");
golden_test!(golden_fixtures_sprite_svgTextBold_puml, "fixtures/sprite/svgTextBold.puml");
golden_test!(golden_fixtures_sprite_svgTextDecoration_puml, "fixtures/sprite/svgTextDecoration.puml");
golden_test!(golden_fixtures_sprite_svgTextItalic_puml, "fixtures/sprite/svgTextItalic.puml");
golden_test!(golden_fixtures_sprite_svgTextStyleAttr_puml, "fixtures/sprite/svgTextStyleAttr.puml");
golden_test!(golden_fixtures_sprite_svgTransformGroup_puml, "fixtures/sprite/svgTransformGroup.puml");
golden_test!(golden_fixtures_sprite_svgTransformMatrix_puml, "fixtures/sprite/svgTransformMatrix.puml");
golden_test!(golden_fixtures_sprite_svgTransformRotate_puml, "fixtures/sprite/svgTransformRotate.puml");
golden_test!(golden_fixtures_sprite_svgTransformScale_puml, "fixtures/sprite/svgTransformScale.puml");
golden_test!(golden_fixtures_sprite_svgTransformTranslate_puml, "fixtures/sprite/svgTransformTranslate.puml");
golden_test!(golden_fixtures_sprite_svgUseDefs_puml, "fixtures/sprite/svgUseDefs.puml");
golden_test!(golden_fixtures_sprite_svgVerticalGradient_puml, "fixtures/sprite/svgVerticalGradient.puml");
golden_test!(golden_fixtures_sprite_testGradientSprite_puml, "fixtures/sprite/testGradientSprite.puml");
golden_test!(golden_fixtures_sprite_testPolylineSprites_puml, "fixtures/sprite/testPolylineSprites.puml");
golden_test!(golden_fixtures_state_scxml0001_puml, "fixtures/state/scxml0001.puml");
golden_test!(golden_fixtures_state_scxml0002_puml, "fixtures/state/scxml0002.puml");
golden_test!(golden_fixtures_state_scxml0003_puml, "fixtures/state/scxml0003.puml");
golden_test!(golden_fixtures_state_scxml0004_puml, "fixtures/state/scxml0004.puml");
golden_test!(golden_fixtures_state_scxml0005_puml, "fixtures/state/scxml0005.puml");
golden_test!(golden_fixtures_state_state_choice001_puml, "fixtures/state/state_choice001.puml");
golden_test!(golden_fixtures_state_state_concurrent001_puml, "fixtures/state/state_concurrent001.puml");
golden_test!(golden_fixtures_state_state_fork001_puml, "fixtures/state/state_fork001.puml");
golden_test!(golden_fixtures_state_state_history001_puml, "fixtures/state/state_history001.puml");
golden_test!(golden_fixtures_state_state_monoline_01_puml, "fixtures/state/state_monoline_01.puml");
golden_test!(golden_fixtures_state_state_monoline_02_puml, "fixtures/state/state_monoline_02.puml");
golden_test!(golden_fixtures_state_state_monoline_03_puml, "fixtures/state/state_monoline_03.puml");
golden_test!(golden_fixtures_state_state_note001_puml, "fixtures/state/state_note001.puml");
golden_test!(golden_fixtures_timing_timingmessagearrowfont_0001_puml, "fixtures/timing/timingmessagearrowfont_0001.puml");
golden_test!(golden_fixtures_timing_timingmessagearrowfont_0002_puml, "fixtures/timing/timingmessagearrowfont_0002.puml");
golden_test!(golden_fixtures_usecase_basic_puml, "fixtures/usecase/basic.puml");
golden_test!(golden_fixtures_usecase_boundary_puml, "fixtures/usecase/boundary.puml");
golden_test!(golden_fixtures_usecase_colon_actor_puml, "fixtures/usecase/colon_actor.puml");
golden_test!(golden_fixtures_wbs_link_url_tooltip_01_puml, "fixtures/wbs/link_url_tooltip_01.puml");
golden_test!(golden_fixtures_wbs_link_url_tooltip_02_puml, "fixtures/wbs/link_url_tooltip_02.puml");
golden_test!(golden_fixtures_wbs_link_url_tooltip_03_puml, "fixtures/wbs/link_url_tooltip_03.puml");
golden_test!(golden_fixtures_wbs_wbs_arrow_puml, "fixtures/wbs/wbs_arrow.puml");
golden_test!(golden_fixtures_wbs_wbs_direction_puml, "fixtures/wbs/wbs_direction.puml");
golden_test!(golden_fixtures_yaml_basic_puml, "fixtures/yaml/basic.puml");

// Total: 296 golden tests
