// Cross-language verification: Rust klimt output must match Java PlantUML exactly.
// Expected values from tests/fixtures/klimt_verify.json (generated by KlimtVerify.java)

use plantuml_little::klimt;

// ═══ Helper ═══════════════════════════════════════════════════════════

fn assert_close(name: &str, actual: f64, expected: f64) {
    assert!(
        (actual - expected).abs() < 1e-9,
        "{}: expected {}, got {}",
        name, expected, actual
    );
}

// ═══ 1. Color resolution ══════════════════════════════════════════════

#[test]
fn color_named_matches_java() {
    let cases: &[(&str, &str)] = &[
        ("red", "#FF0000"),
        ("blue", "#0000FF"),
        ("green", "#008000"),
        ("yellow", "#FFFF00"),
        ("black", "#000000"),
        ("white", "#FFFFFF"),
        ("LightBlue", "#ADD8E6"),
        ("DarkSalmon", "#E9967A"),
        ("Gold", "#FFD700"),
        ("Navy", "#000080"),
        ("Crimson", "#DC143C"),
        ("Lavender", "#E6E6FA"),
        ("Aquamarine", "#7FFFD4"),
        ("Chocolate", "#D2691E"),
        ("Indigo", "#4B0082"),
        ("Lime", "#00FF00"),
        ("Olive", "#808000"),
        ("Teal", "#008080"),
    ];
    for &(name, expected) in cases {
        let color = klimt::color::resolve_color(name)
            .unwrap_or_else(|| panic!("color '{}' not resolved", name));
        assert_eq!(
            color.to_svg(), expected,
            "color '{}': expected {}, got {}", name, expected, color.to_svg()
        );
    }
}

#[test]
fn color_transparent_matches_java() {
    // Java returns "#00000000" for transparent
    let c = klimt::color::resolve_color("transparent").unwrap();
    assert!(c.is_none() || c.is_transparent(), "transparent should be none/transparent");
}

#[test]
fn color_archimate_matches_java() {
    let cases: &[(&str, &str)] = &[
        ("APPLICATION", "#C2F0FF"),
        ("BUSINESS", "#FFFFCC"),
        ("TECHNOLOGY", "#C9FFC9"),
    ];
    for &(name, expected) in cases {
        let color = klimt::color::resolve_color(name)
            .unwrap_or_else(|| panic!("archimate color '{}' not resolved", name));
        assert_eq!(color.to_svg(), expected, "archimate '{}'", name);
    }
}

// ═══ 2. HColor methods ════════════════════════════════════════════════

#[test]
fn color_is_dark_matches_java() {
    use klimt::color::HColor;
    // Java: black is dark, white is not, red is dark
    assert!(HColor::rgb(0, 0, 0).is_dark(), "black should be dark");
    assert!(!HColor::rgb(255, 255, 255).is_dark(), "white should not be dark");
    assert!(HColor::rgb(255, 0, 0).is_dark(), "red should be dark");
}

// ═══ 3. UStroke ════════════════════════════════════════════════════════

#[test]
fn ustroke_matches_java() {
    let dashed = klimt::UStroke::new(5.0, 5.0, 1.0);
    assert_close("dash_vis", dashed.dash_visible, 5.0);
    assert_close("dash_spc", dashed.dash_space, 5.0);
    assert_close("dash_thick", dashed.thickness, 1.0);
    let da = dashed.dasharray_svg().unwrap();
    assert_close("dasharray_0", da.0, 5.0);
    assert_close("dasharray_1", da.1, 5.0);

    let solid = klimt::UStroke::with_thickness(1.5);
    assert!(solid.dasharray_svg().is_none(), "solid should have no dash");
    assert_close("solid_thick", solid.thickness, 1.5);

    let simple = klimt::UStroke::simple();
    assert_close("simple_thick", simple.thickness, 1.0);
}

// ═══ 4. UTranslate ════════════════════════════════════════════════════

#[test]
fn utranslate_matches_java() {
    let t1 = klimt::UTranslate::new(10.0, 20.0);
    let t2 = klimt::UTranslate::new(5.0, -3.0);

    let t3 = t1.compose(t2);
    assert_close("compose_dx", t3.dx, 15.0);
    assert_close("compose_dy", t3.dy, 17.0);

    let t4 = t1.reverse();
    assert_close("reverse_dx", t4.dx, -10.0);
    assert_close("reverse_dy", t4.dy, -20.0);

    let t5 = t1.scaled(2.0);
    assert_close("scaled_dx", t5.dx, 20.0);
    assert_close("scaled_dy", t5.dy, 40.0);
}

// ═══ 5. XPoint2D ══════════════════════════════════════════════════════

#[test]
fn xpoint2d_matches_java() {
    use klimt::geom::XPoint2D;
    assert_close("dist_3_4", XPoint2D::distance_between(0.0, 0.0, 3.0, 4.0), 5.0);
    let p1 = XPoint2D::new(10.0, 20.0);
    let p2 = XPoint2D::new(13.0, 24.0);
    assert_close("dist_p1_p2", p1.distance(&p2), 5.0);
}

// ═══ 6. XDimension2D ══════════════════════════════════════════════════

#[test]
fn xdimension2d_matches_java() {
    use klimt::geom::XDimension2D;
    let d1 = XDimension2D::new(100.0, 50.0);
    let d2 = XDimension2D::new(80.0, 30.0);

    let tb = d1.merge_vertical(&d2);
    assert_close("tb_w", tb.width, 100.0);
    assert_close("tb_h", tb.height, 80.0);

    let lr = d1.merge_horizontal(&d2);
    assert_close("lr_w", lr.width, 180.0);
    assert_close("lr_h", lr.height, 50.0);

    let mx = d1.max(&d2);
    assert_close("max_w", mx.width, 100.0);
    assert_close("max_h", mx.height, 50.0);

    let dl = d1.delta(10.0, -5.0);
    assert_close("delta_w", dl.width, 110.0);
    assert_close("delta_h", dl.height, 45.0);
}

// ═══ 7. XLine2D ═══════════════════════════════════════════════════════

#[test]
fn xline2d_matches_java() {
    use klimt::geom::{XLine2D, XPoint2D};
    let line = XLine2D::from_points(XPoint2D::new(0.0, 0.0), XPoint2D::new(10.0, 0.0));
    let mid = line.middle();
    assert_close("mid_x", mid.x, 5.0);
    assert_close("mid_y", mid.y, 0.0);
    assert_close("angle_horiz", line.angle(), 0.0);

    let line2 = XLine2D::from_points(XPoint2D::new(0.0, 0.0), XPoint2D::new(0.0, 10.0));
    assert_close("angle_vert", line2.angle(), std::f64::consts::FRAC_PI_2);
}

// ═══ 8. URectangle ════════════════════════════════════════════════════

#[test]
fn urectangle_matches_java() {
    use klimt::shape::URectangle;
    let rect = URectangle::build(100.0, 50.0);
    assert_close("rect_w", rect.width, 100.0);
    assert_close("rect_h", rect.height, 50.0);

    let rr = rect.rounded(10.0);
    assert_close("rect_rx", rr.rx, 10.0);
    assert_close("rect_ry", rr.ry, 10.0);
}

// ═══ 9. UEllipse ══════════════════════════════════════════════════════

#[test]
fn uellipse_matches_java() {
    use klimt::shape::UEllipse;
    let ell = UEllipse::build(80.0, 60.0);
    assert_close("ell_w", ell.width, 80.0);
    assert_close("ell_h", ell.height, 60.0);

    // Point at angle 0: rightmost
    let ep = ell.point_at_angle(0.0);
    assert_close("ell_pt0_x", ep.x, 80.0);
    assert_close("ell_pt0_y", ep.y, 30.0);

    // Point at angle PI: leftmost
    let ep2 = ell.point_at_angle(std::f64::consts::PI);
    assert!(ep2.x.abs() < 1e-9, "ell_ptPI_x should be ~0, got {}", ep2.x);
    assert_close("ell_ptPI_y", ep2.y, 30.0);
}

// ═══ 10. ULine ════════════════════════════════════════════════════════

#[test]
fn uline_matches_java() {
    use klimt::shape::ULine;
    let h = ULine::hline(100.0);
    assert_close("uline_h_dx", h.dx, 100.0);
    assert_close("uline_h_dy", h.dy, 0.0);

    let v = ULine::vline(50.0);
    assert_close("uline_v_dx", v.dx, 0.0);
    assert_close("uline_v_dy", v.dy, 50.0);
}

// ═══ 11. Number formatting (CRITICAL for SVG matching) ════════════════

#[test]
fn number_format_matches_java() {
    use klimt::svg::test_helpers::fmt_at_scale_1;

    let cases: &[(f64, &str)] = &[
        (0.0, "0"),
        (42.0, "42"),
        (1.5, "1.5"),
        (1.23456, "1.2346"),
        // Java returns "-0" for -0.00004; we allow "0" or "-0"
        (30.2969, "30.2969"),
        (47.667, "47.667"),
        (0.5, "0.5"),
        (24.9951, "24.9951"),
        (33.667, "33.667"),
        (114.5625, "114.5625"),
        (36.2969, "36.2969"),
        (167.6152, "167.6152"),
        (5.0, "5"),
        (2.5, "2.5"),
        (13.9688, "13.9688"),
        (7.0, "7"),
        (1.0, "1"),
    ];
    for &(value, expected) in cases {
        let actual = fmt_at_scale_1(value);
        assert_eq!(
            actual, expected,
            "fmt({}): expected '{}', got '{}'",
            value, expected, actual
        );
    }
}

// ═══ 12. SVG element attribute order verification ═════════════════════

#[test]
fn svg_rect_attribute_order_matches_java() {
    use klimt::svg::SvgGraphic;
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#E2E2F0");
    svg.set_stroke_color(Some("#181818"));
    svg.set_stroke_width(0.5, None);
    svg.svg_rectangle(5.0, 5.0, 47.667, 30.2969, 2.5, 2.5, 0.0);
    let body = svg.body();

    // Verify exact Java DOM alphabetical attribute order: fill < height < rx < ry < style < width < x < y
    let fill_pos = body.find("fill=").expect("fill");
    let height_pos = body.find("height=").expect("height");
    let rx_pos = body.find("rx=").expect("rx");
    let style_pos = body.find("style=").expect("style");
    let width_pos = body.find("width=").expect("width");
    let x_pos = body.find(" x=").expect("x");
    let y_pos = body.find(" y=").expect("y");
    assert!(fill_pos < height_pos, "fill < height");
    assert!(height_pos < rx_pos, "height < rx");
    assert!(rx_pos < style_pos, "rx < style");
    assert!(style_pos < width_pos, "style < width");
    assert!(width_pos < x_pos, "width < x");
    assert!(x_pos < y_pos, "x < y");
}

#[test]
fn svg_text_attribute_order_matches_java() {
    use klimt::svg::{SvgGraphic, LengthAdjust};
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_fill_color("#000000");
    svg.svg_text("Alice", 12.0, 24.9951, Some("sans-serif"), 14.0,
                 None, None, None, 33.667, LengthAdjust::Spacing, None, 0);
    let body = svg.body();

    // Java reference: fill, font-family, font-size, lengthAdjust, textLength, x, y
    assert!(body.contains("fill="), "has fill");
    assert!(body.contains("font-family=\"sans-serif\""), "has font-family");
    assert!(body.contains("font-size=\"14\""), "has font-size");
    assert!(body.contains("lengthAdjust=\"spacing\""), "has lengthAdjust");
    assert!(body.contains("textLength=\"33.667\""), "has textLength");
    assert!(body.contains(">Alice</text>"), "has text content");
}

// ═══ 13. SVG root element matches Java format ═════════════════════════

#[test]
fn svg_root_element_matches_java_format() {
    use klimt::svg::SvgGraphic;
    let mut svg = SvgGraphic::new(12345, 1.0);
    svg.set_max(115, 122);
    let doc = svg.to_svg(Some("#FFFFFF"), "SEQUENCE");

    // Compare with Java's exact output from diag0_root
    let expected_start = r#"<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentStyleType="text/css" data-diagram-type="SEQUENCE""#;
    assert!(doc.starts_with(expected_start),
        "SVG root should start with:\n{}\nbut got:\n{}",
        expected_start, &doc[..doc.len().min(200)]);

    // Check key attributes present
    assert!(doc.contains(r#"height="122px""#), "height");
    assert!(doc.contains(r#"preserveAspectRatio="none""#), "preserveAspectRatio");
    assert!(doc.contains(r#"style="width:115px;height:122px;background:#FFFFFF;""#), "style");
    assert!(doc.contains(r#"version="1.1""#), "version");
    assert!(doc.contains(r#"viewBox="0 0 115 122""#), "viewBox");
    assert!(doc.contains(r#"width="115px""#), "width");
    assert!(doc.contains(r#"zoomAndPan="magnify">"#), "zoomAndPan");
}
