// Auto-generated by tests/generate_test_list.py
// Do not edit manually. Regenerate with:
//   python3 tests/generate_test_list.py > tests/reference_tests.rs

use base64::Engine;
use std::fs;
use std::path::Path;

fn convert_fixture(path: &str) -> String {
    let source = fs::read_to_string(path).unwrap_or_else(|e| panic!("cannot read {path}: {e}"));
    plantuml_little::convert_with_input_path(&source, Path::new(path))
        .unwrap_or_else(|e| panic!("convert {path} failed: {e}"))
}

fn load_reference(fixture_path: &str) -> Option<String> {
    let reference_path = fixture_path
        .replace("fixtures/", "reference/")
        .replace(".puml", ".svg");
    fs::read_to_string(&reference_path).ok()
}

fn find_first_diff(a: &str, b: &str) -> (usize, usize, String) {
    let mut line = 1;
    let mut col = 1;
    for (i, (ca, cb)) in a.chars().zip(b.chars()).enumerate() {
        if ca != cb {
            let context_a = &a[i.saturating_sub(40)..a.len().min(i + 40)];
            let context_b = &b[i.saturating_sub(40)..b.len().min(i + 40)];
            return (
                line,
                col,
                format!(
                    "expected: ...{}...\nactual:   ...{}...",
                    context_b, context_a
                ),
            );
        }
        if ca == '\n' {
            line += 1;
            col = 1;
        } else {
            col += 1;
        }
    }
    let la = a.len();
    let lb = b.len();
    (
        line,
        col,
        format!("length differs: actual={la}, expected={lb}"),
    )
}

fn strip_plantuml_src_pi(s: &str) -> String {
    // Remove <?plantuml-src ...?> PI since deflate output is implementation-specific
    let mut result = s.to_string();
    while let Some(start) = result.find("<?plantuml-src ") {
        if let Some(end) = result[start..].find("?>") {
            result.replace_range(start..start + end + 2, "");
        } else {
            break;
        }
    }
    result
}

/// Normalize inline PNG base64 data URIs to a canonical form.
/// Different deflate implementations produce different compressed output for the same
/// pixel data. To compare visual equivalence, decode each PNG, extract raw pixel data,
/// and re-encode with a canonical compressor.
fn normalize_inline_pngs(s: &str) -> String {
    use std::io::Read;
    let marker = "data:image/png;base64,";
    let mut result = String::with_capacity(s.len());
    let mut pos = 0;
    while let Some(start) = s[pos..].find(marker) {
        let abs_start = pos + start;
        result.push_str(&s[pos..abs_start + marker.len()]);
        let b64_start = abs_start + marker.len();
        // Find end of base64 (next '"' or non-base64 char)
        let b64_end = s[b64_start..]
            .find(|c: char| c == '"' || c == '\'' || c == '<' || c == ' ')
            .map_or(s.len(), |e| b64_start + e);
        let b64 = &s[b64_start..b64_end];

        // Try to decode, decompress, and re-encode canonically
        if let Ok(png_data) = base64::engine::general_purpose::STANDARD.decode(b64) {
            if let Some(canonical) = canonicalize_png(&png_data) {
                let new_b64 = base64::engine::general_purpose::STANDARD.encode(&canonical);
                result.push_str(&new_b64);
                pos = b64_end;
                continue;
            }
        }
        // Fallback: keep original
        result.push_str(b64);
        pos = b64_end;
    }
    result.push_str(&s[pos..]);
    result
}

/// Re-encode a PNG with a canonical zlib compressor to normalize compression differences.
fn canonicalize_png(png: &[u8]) -> Option<Vec<u8>> {
    use flate2::read::ZlibDecoder;
    use flate2::write::ZlibEncoder;
    use std::io::Read;
    use std::io::Write;

    // Verify PNG signature
    if png.len() < 8 || &png[..8] != &[137, 80, 78, 71, 13, 10, 26, 10] {
        return None;
    }

    let mut ihdr_data = Vec::new();
    let mut raw_pixels = Vec::new();
    let mut pos = 8usize;

    while pos + 12 <= png.len() {
        let length = u32::from_be_bytes(png[pos..pos + 4].try_into().ok()?) as usize;
        if pos + 12 + length > png.len() {
            break;
        }
        let chunk_type = &png[pos + 4..pos + 8];
        let chunk_data = &png[pos + 8..pos + 8 + length];

        match chunk_type {
            b"IHDR" => ihdr_data = chunk_data.to_vec(),
            b"IDAT" => {
                let mut decoder = ZlibDecoder::new(chunk_data);
                decoder.read_to_end(&mut raw_pixels).ok()?;
            }
            _ => {}
        }
        pos += 12 + length;
    }

    if ihdr_data.is_empty() || raw_pixels.is_empty() {
        return None;
    }

    // Re-encode with level 0 (no compression) for canonical, minimal output
    let mut buf = Vec::new();
    buf.extend_from_slice(&[137, 80, 78, 71, 13, 10, 26, 10]);

    // IHDR
    write_test_png_chunk(&mut buf, b"IHDR", &ihdr_data);

    // IDAT with canonical compression (level 0 = store)
    let mut encoder = ZlibEncoder::new(Vec::new(), flate2::Compression::none());
    encoder.write_all(&raw_pixels).ok()?;
    let compressed = encoder.finish().ok()?;
    write_test_png_chunk(&mut buf, b"IDAT", &compressed);

    // IEND
    write_test_png_chunk(&mut buf, b"IEND", &[]);

    Some(buf)
}

fn write_test_png_chunk(buf: &mut Vec<u8>, chunk_type: &[u8; 4], data: &[u8]) {
    buf.extend_from_slice(&(data.len() as u32).to_be_bytes());
    buf.extend_from_slice(chunk_type);
    buf.extend_from_slice(data);
    let mut crc = 0xFFFF_FFFFu32;
    for &byte in chunk_type.iter().chain(data.iter()) {
        for bit in 0..8 {
            if (crc ^ byte as u32) & (1 << bit) != 0 {
                crc = (crc >> 1) ^ 0xEDB88320;
            } else {
                crc >>= 1;
            }
        }
    }
    buf.extend_from_slice(&(crc ^ 0xFFFF_FFFF).to_be_bytes());
}

/// Extract a numeric token spanning position `pos` in the string.
/// Returns (start, end, parsed_value) or None.
fn extract_number_at(s: &str, pos: usize) -> Option<(usize, usize, f64)> {
    let bytes = s.as_bytes();
    if pos >= bytes.len() {
        return None;
    }
    // Must be inside a digit or decimal point
    if !matches!(bytes[pos], b'0'..=b'9' | b'.' | b'-') {
        return None;
    }
    // Walk back to find start
    let mut start = pos;
    while start > 0 && matches!(bytes[start - 1], b'0'..=b'9' | b'.' | b'-') {
        start -= 1;
    }
    // Walk forward to find end
    let mut end = pos;
    while end < bytes.len() && matches!(bytes[end], b'0'..=b'9' | b'.') {
        end += 1;
    }
    if start == end {
        return None;
    }
    s[start..end].parse::<f64>().ok().map(|v| (start, end, v))
}

/// Normalize SVG filter IDs to canonical sequential form.
/// Filter definitions use implementation-specific hash IDs; replace them
/// with sequential `__f0__`, `__f1__`, etc. based on order of appearance.
fn normalize_filter_ids(s: &str) -> String {
    use std::collections::HashMap;
    let mut result = s.to_string();
    let mut id_map: HashMap<String, String> = HashMap::new();
    let mut counter = 0usize;

    // Find all id="..." in <filter> and gradient elements
    for tag_prefix in &["<filter ", "<linearGradient ", "<radialGradient "] {
        let mut search_from = 0;
        loop {
            let tag_pos = match result[search_from..].find(tag_prefix) {
                Some(p) => search_from + p,
                None => break,
            };
            let id_pos = match result[tag_pos..].find("id=\"") {
                Some(p) => tag_pos + p + 4,
                None => {
                    search_from = tag_pos + tag_prefix.len();
                    continue;
                }
            };
            let id_end = match result[id_pos..].find('"') {
                Some(p) => id_pos + p,
                None => {
                    search_from = id_pos;
                    continue;
                }
            };
            let old_id = result[id_pos..id_end].to_string();
            if !id_map.contains_key(&old_id) {
                let new_id = format!("__f{}__", counter);
                id_map.insert(old_id.clone(), new_id);
                counter += 1;
            }
            search_from = id_end + 1;
        }
    }

    // Replace IDs in attribute contexts only (not in text content).
    // Match patterns: id="ID", url(#ID), xlink:href="#ID"
    for (old_id, new_id) in &id_map {
        // id="old_id"
        result = result.replace(&format!("id=\"{old_id}\""), &format!("id=\"{new_id}\""));
        // url(#old_id)
        result = result.replace(&format!("url(#{old_id})"), &format!("url(#{new_id})"));
        // xlink:href="#old_id"
        result = result.replace(
            &format!("xlink:href=\"#{old_id}\""),
            &format!("xlink:href=\"#{new_id}\""),
        );
        // href="#old_id"
        result = result.replace(
            &format!("href=\"#{old_id}\""),
            &format!("href=\"#{new_id}\""),
        );
        // filter="url(#old_id)"
        result = result.replace(
            &format!("filter=\"url(#{old_id})\""),
            &format!("filter=\"url(#{new_id})\""),
        );
    }
    result
}

/// Normalize entity/link IDs to canonical sequential form.
/// Java's quark-based ID assignment differs from Rust's sequential allocation,
/// so normalize `id="ent0002"`, `id="lnk3"`, `data-entity-1="ent0002"`, etc.
/// to canonical `__e0__`, `__l0__` based on first-appearance order.
fn normalize_entity_link_ids(s: &str) -> String {
    use std::collections::HashMap;
    let mut result = s.to_string();

    // Collect entity IDs in order of appearance
    let mut ent_map: HashMap<String, String> = HashMap::new();
    let mut ent_counter = 0usize;
    {
        let mut pos = 0;
        while let Some(idx) = result[pos..].find("id=\"ent") {
            let abs = pos + idx + 4; // start of "ent..."
            if let Some(end) = result[abs..].find('"') {
                let old_id = result[abs..abs + end].to_string();
                if !ent_map.contains_key(&old_id) {
                    ent_map.insert(old_id, format!("__e{}__", ent_counter));
                    ent_counter += 1;
                }
                pos = abs + end + 1;
            } else {
                break;
            }
        }
    }

    // Collect link IDs in order of appearance
    let mut lnk_map: HashMap<String, String> = HashMap::new();
    let mut lnk_counter = 0usize;
    {
        let mut pos = 0;
        while let Some(idx) = result[pos..].find("id=\"lnk") {
            let abs = pos + idx + 4; // start of "lnk..."
            if let Some(end) = result[abs..].find('"') {
                let old_id = result[abs..abs + end].to_string();
                if !lnk_map.contains_key(&old_id) {
                    lnk_map.insert(old_id, format!("__l{}__", lnk_counter));
                    lnk_counter += 1;
                }
                pos = abs + end + 1;
            } else {
                break;
            }
        }
    }

    // Replace entity IDs in all contexts
    for (old_id, new_id) in &ent_map {
        result = result.replace(&format!("id=\"{old_id}\""), &format!("id=\"{new_id}\""));
        result = result.replace(
            &format!("data-entity-1=\"{old_id}\""),
            &format!("data-entity-1=\"{new_id}\""),
        );
        result = result.replace(
            &format!("data-entity-2=\"{old_id}\""),
            &format!("data-entity-2=\"{new_id}\""),
        );
    }

    // Replace link IDs
    for (old_id, new_id) in &lnk_map {
        result = result.replace(&format!("id=\"{old_id}\""), &format!("id=\"{new_id}\""));
    }

    result
}

/// Strip implementation-specific data attributes that differ between Java and Rust
/// but do not affect visual output:
/// - `data-source-line="N"`: line number references differ due to counting differences
/// - `data-entity-1/2="X"`: entity ID references depend on rendering order which may differ
fn strip_nonvisual_data_attrs(s: &str) -> String {
    let re = regex::Regex::new(
        r#" data-(?:source-line|entity-[12])="[^"]*""#,
    )
    .unwrap();
    re.replace_all(s, "").to_string()
}

fn assert_exact_match(actual: &str, reference: &str, path: &str) {
    if actual == reference {
        return;
    }
    // Allow deflate-encoding differences in <?plantuml-src?> PI and inline PNGs
    let a = normalize_inline_pngs(&normalize_entity_link_ids(&normalize_filter_ids(&strip_nonvisual_data_attrs(&strip_plantuml_src_pi(actual)))));
    let r = normalize_inline_pngs(&normalize_entity_link_ids(&normalize_filter_ids(&strip_nonvisual_data_attrs(&strip_plantuml_src_pi(reference)))));
    if a == r {
        return;
    }

    // Fuzzy numeric comparison: tolerate differences < 0.01 in numeric values
    let a_bytes = a.as_bytes();
    let r_bytes = r.as_bytes();
    let mut ai = 0usize;
    let mut ri = 0usize;
    let mut fuzzy_skips = 0usize;
    while ai < a_bytes.len() && ri < r_bytes.len() {
        if a_bytes[ai] == r_bytes[ri] {
            ai += 1;
            ri += 1;
            continue;
        }
        // Mismatch — check if both sides are inside or at the boundary of a number.
        // For boundary cases (ai past the number), look back one char.
        let a_num = extract_number_at(&a, ai).or_else(|| {
            if ai > 0 {
                extract_number_at(&a, ai - 1)
            } else {
                None
            }
        });
        let r_num = extract_number_at(&r, ri).or_else(|| {
            if ri > 0 {
                extract_number_at(&r, ri - 1)
            } else {
                None
            }
        });
        if let (Some((a_start, a_end, a_val)), Some((r_start, r_end, r_val))) = (a_num, r_num) {
            if (a_val - r_val).abs() < 0.01 {
                ai = if a_end > ai {
                    a_end
                } else if a_start < ai {
                    ai
                } else {
                    ai + 1
                };
                ri = if r_end > ri {
                    r_end
                } else if r_start < ri {
                    ri
                } else {
                    ri + 1
                };
                fuzzy_skips += 1;
                if fuzzy_skips > 200 {
                    // Too many numeric differences — this SVG has structural mismatches
                    let (line, col, ctx) = find_first_diff(&a, &r);
                    panic!("{path}: output differs from reference at line {line} col {col}\n{ctx}");
                }
                continue;
            }
        }
        // Real mismatch
        let (line, col, ctx) = find_first_diff(&a, &r);
        panic!("{path}: output differs from reference at line {line} col {col}\n{ctx}");
    }
    // Check length difference
    if ai != a_bytes.len() || ri != r_bytes.len() {
        // Allow trailing length difference only if remaining is whitespace
        let a_tail = a[ai..].trim();
        let r_tail = r[ri..].trim();
        if !a_tail.is_empty() && !r_tail.is_empty() {
            let (line, col, ctx) = find_first_diff(&a, &r);
            panic!("{path}: output differs from reference at line {line} col {col}\n{ctx}");
        }
    }
}

fn assert_no_raw_markup(svg: &str, path: &str) {
    let raw_patterns: &[(&str, &str)] = &[
        ("<$", "raw sprite reference <$...>"),
        ("<size:", "raw <size:N> markup"),
        ("<color:", "raw <color:X> markup"),
        ("<back:", "raw <back:X> markup"),
        ("<font:", "raw <font:X> markup"),
    ];
    let escaped_patterns: &[(&str, &str)] = &[
        ("&lt;size:", "escaped <size:N> markup"),
        ("&lt;color:", "escaped <color:X> markup"),
        ("&lt;back:", "escaped <back:X> markup"),
        ("&lt;font:", "escaped <font:X> markup"),
        ("&lt;$", "escaped sprite reference <$...>"),
    ];
    for (pat, desc) in raw_patterns {
        assert!(!svg.contains(pat), "{path}: {desc} in SVG output");
    }
    // Check for escaped markup only outside monospace/code text elements.
    // Inside <code> blocks, escaped markup like &lt;color:X&gt; is legitimate
    // literal text and should not be flagged.
    for (pat, desc) in escaped_patterns {
        if let Some(idx) = svg.find(pat) {
            // Check if this occurrence is inside a monospace text element
            let before = &svg[..idx];
            let is_in_monospace = before
                .rfind("<text ")
                .map(|text_start| {
                    let text_tag = &before[text_start..];
                    text_tag.contains("font-family=\"monospace\"")
                })
                .unwrap_or(false);
            if !is_in_monospace {
                panic!("{path}: {desc} in SVG output");
            }
        }
    }
    for line in svg.lines() {
        if let Some(start) = line.find('>') {
            if let Some(end) = line.rfind("</text>") {
                let text_content = &line[start + 1..end];
                if text_content.contains("**") {
                    panic!("{path}: unprocessed Creole bold **...** in text: {text_content}");
                }
            }
        }
    }
}

macro_rules! reference_test {
    ($name:ident, $fixture:expr) => {
        #[test]
        fn $name() {
            let fixture = concat!("tests/", $fixture);
            let svg = convert_fixture(fixture);
            assert_no_raw_markup(&svg, fixture);
            // UPDATE_REF=1 cargo test ... to overwrite reference SVGs with current output
            if std::env::var("UPDATE_REF").is_ok() {
                let ref_path = fixture
                    .replace("fixtures/", "reference/")
                    .replace(".puml", ".svg");
                fs::write(&ref_path, &svg).unwrap_or_else(|e| panic!("write {ref_path}: {e}"));
                return;
            }
            if let Some(reference) = load_reference(fixture) {
                assert_exact_match(&svg, &reference, fixture);
            }
        }
    };
}

reference_test!(
    reference_fixtures_archimate_basic_puml,
    "fixtures/archimate/basic.puml"
);
reference_test!(
    reference_fixtures_chart_bar_basic_puml,
    "fixtures/chart/bar_basic.puml"
);
reference_test!(
    reference_fixtures_files_diagram_basic_puml,
    "fixtures/files_diagram/basic.puml"
);
reference_test!(
    reference_fixtures_activity_a0002_puml,
    "fixtures/activity/a0002.puml"
);
reference_test!(
    reference_fixtures_activity_activity_creole_table_01_puml,
    "fixtures/activity/activity_creole_table_01.puml"
);
reference_test!(
    reference_fixtures_activity_activity_creole_table_02_puml,
    "fixtures/activity/activity_creole_table_02.puml"
);
reference_test!(
    reference_fixtures_activity_activity_mono_multi_line_puml,
    "fixtures/activity/activity_mono_multi_line.puml"
);
reference_test!(
    reference_fixtures_activity_activity_mono_multi_line2_puml,
    "fixtures/activity/activity_mono_multi_line2.puml"
);
reference_test!(
    reference_fixtures_activity_activity_mono_multi_line2_v2_puml,
    "fixtures/activity/activity_mono_multi_line2_v2.puml"
);
reference_test!(
    reference_fixtures_activity_activity_mono_multi_line_v2_puml,
    "fixtures/activity/activity_mono_multi_line_v2.puml"
);
reference_test!(
    reference_fixtures_activity_swimlane001_puml,
    "fixtures/activity/swimlane001.puml"
);
reference_test!(
    reference_fixtures_class_a0005_puml,
    "fixtures/class/a0005.puml"
);
reference_test!(
    reference_fixtures_class_class_funcparam_arrow_01_puml,
    "fixtures/class/class_funcparam_arrow_01.puml"
);
reference_test!(
    reference_fixtures_class_class_funcparam_arrow_02_puml,
    "fixtures/class/class_funcparam_arrow_02.puml"
);
reference_test!(
    reference_fixtures_class_colors001_puml,
    "fixtures/class/colors001.puml"
);
reference_test!(
    reference_fixtures_class_generics001_puml,
    "fixtures/class/generics001.puml"
);
reference_test!(
    reference_fixtures_class_hideshow001_puml,
    "fixtures/class/hideshow001.puml"
);
reference_test!(
    reference_fixtures_class_hideshow002_puml,
    "fixtures/class/hideshow002.puml"
);
reference_test!(
    reference_fixtures_class_hideshow003_puml,
    "fixtures/class/hideshow003.puml"
);
reference_test!(
    reference_fixtures_class_hideshow004_puml,
    "fixtures/class/hideshow004.puml"
);
reference_test!(
    reference_fixtures_class_qualifiedassoc001_puml,
    "fixtures/class/qualifiedassoc001.puml"
);
reference_test!(
    reference_fixtures_class_qualifiedassoc002_puml,
    "fixtures/class/qualifiedassoc002.puml"
);
reference_test!(
    reference_fixtures_class_xmi0002_puml,
    "fixtures/class/xmi0002.puml"
);
reference_test!(
    reference_fixtures_class_xmi0003_puml,
    "fixtures/class/xmi0003.puml"
);
reference_test!(
    reference_fixtures_class_xmi0004_puml,
    "fixtures/class/xmi0004.puml"
);
reference_test!(
    reference_fixtures_component_buitin_newline_chr_puml,
    "fixtures/component/buitin_newline_chr.puml"
);
reference_test!(
    reference_fixtures_component_colors001_puml,
    "fixtures/component/colors001.puml"
);
reference_test!(
    reference_fixtures_component_componentextraarrows_0001_puml,
    "fixtures/component/componentextraarrows_0001.puml"
);
reference_test!(
    reference_fixtures_component_deployment01_puml,
    "fixtures/component/deployment01.puml"
);
reference_test!(
    reference_fixtures_component_deployment_last_name_multi_line_puml,
    "fixtures/component/deployment_last_name_multi_line.puml"
);
reference_test!(
    reference_fixtures_component_gml0000_puml,
    "fixtures/component/gml0000.puml"
);
reference_test!(
    reference_fixtures_component_gml0001_puml,
    "fixtures/component/gml0001.puml"
);
reference_test!(
    reference_fixtures_component_jaws5_puml,
    "fixtures/component/jaws5.puml"
);
reference_test!(
    reference_fixtures_component_subdiagram_theme_02_puml,
    "fixtures/component/subdiagram_theme_02.puml"
);
reference_test!(
    reference_fixtures_component_xmi0001_puml,
    "fixtures/component/xmi0001.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws1_puml,
    "fixtures/dev/jaws/jaws1.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws10_puml,
    "fixtures/dev/jaws/jaws10.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws11_puml,
    "fixtures/dev/jaws/jaws11.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws12_puml,
    "fixtures/dev/jaws/jaws12.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws2_puml,
    "fixtures/dev/jaws/jaws2.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws3_puml,
    "fixtures/dev/jaws/jaws3.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws4_puml,
    "fixtures/dev/jaws/jaws4.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws5_puml,
    "fixtures/dev/jaws/jaws5.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws6_puml,
    "fixtures/dev/jaws/jaws6.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws7_puml,
    "fixtures/dev/jaws/jaws7.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws8_puml,
    "fixtures/dev/jaws/jaws8.puml"
);
reference_test!(
    reference_fixtures_dev_jaws_jaws9_puml,
    "fixtures/dev/jaws/jaws9.puml"
);
reference_test!(
    reference_fixtures_dev_newline_WBS_arrow_puml,
    "fixtures/dev/newline/WBS_arrow.puml"
);
reference_test!(
    reference_fixtures_dev_newline_WBS_direction_puml,
    "fixtures/dev/newline/WBS_direction.puml"
);
reference_test!(
    reference_fixtures_dev_newline_activity_creole_table_puml,
    "fixtures/dev/newline/activity_creole_table.puml"
);
reference_test!(
    reference_fixtures_dev_newline_activity_mono_multi_line_puml,
    "fixtures/dev/newline/activity_mono_multi_line.puml"
);
reference_test!(
    reference_fixtures_dev_newline_activity_mono_multi_line2_puml,
    "fixtures/dev/newline/activity_mono_multi_line2.puml"
);
reference_test!(
    reference_fixtures_dev_newline_builtin_newline_puml,
    "fixtures/dev/newline/builtin_newline.puml"
);
reference_test!(
    reference_fixtures_dev_newline_buitin_newline_chr_puml,
    "fixtures/dev/newline/buitin_newline_chr.puml"
);
reference_test!(
    reference_fixtures_dev_newline_class_funcparam_arrow_puml,
    "fixtures/dev/newline/class_funcparam_arrow.puml"
);
reference_test!(
    reference_fixtures_dev_newline_deployment_last_name_multi_line_puml,
    "fixtures/dev/newline/deployment_last_name_multi_line.puml"
);
reference_test!(
    reference_fixtures_dev_newline_deployment_mono_multi_line_puml,
    "fixtures/dev/newline/deployment_mono_multi_line.puml"
);
reference_test!(
    reference_fixtures_dev_newline_deployment_on_name_puml,
    "fixtures/dev/newline/deployment_on_name.puml"
);
reference_test!(
    reference_fixtures_dev_newline_json_escaped_puml,
    "fixtures/dev/newline/json_escaped.puml"
);
reference_test!(
    reference_fixtures_dev_newline_link_URL_tooltip_puml,
    "fixtures/dev/newline/link_URL_tooltip.puml"
);
reference_test!(
    reference_fixtures_dev_newline_preproc_functionparam_line_continuation_puml,
    "fixtures/dev/newline/preproc_functionparam_line_continuation.puml"
);
reference_test!(
    reference_fixtures_dev_newline_seq_mono_line_puml,
    "fixtures/dev/newline/seq_mono_line.puml"
);
reference_test!(
    reference_fixtures_dev_newline_state_monoline_puml,
    "fixtures/dev/newline/state_monoline.puml"
);
reference_test!(
    reference_fixtures_dev_newline_subdiagram_theme_puml,
    "fixtures/dev/newline/subdiagram_theme.puml"
);
reference_test!(
    reference_fixtures_dev_newlinev2_activity_mono_multi_line2_v2_puml,
    "fixtures/dev/newlinev2/activity_mono_multi_line2_v2.puml"
);
reference_test!(
    reference_fixtures_dev_newlinev2_activity_mono_multi_line_v2_puml,
    "fixtures/dev/newlinev2/activity_mono_multi_line_v2.puml"
);
reference_test!(
    reference_fixtures_ditaa_basic_puml,
    "fixtures/ditaa/basic.puml"
);
reference_test!(reference_fixtures_dot_basic_puml, "fixtures/dot/basic.puml");
reference_test!(
    reference_fixtures_erd_chenmovie_puml,
    "fixtures/erd/chenmovie.puml"
);
reference_test!(
    reference_fixtures_erd_chenmoviealias_puml,
    "fixtures/erd/chenmoviealias.puml"
);
reference_test!(
    reference_fixtures_erd_chenmovieextended_puml,
    "fixtures/erd/chenmovieextended.puml"
);
reference_test!(
    reference_fixtures_erd_chenrankdir_puml,
    "fixtures/erd/chenrankdir.puml"
);
reference_test!(
    reference_fixtures_erd_weak001_puml,
    "fixtures/erd/weak001.puml"
);
reference_test!(
    reference_fixtures_gantt_a0003_puml,
    "fixtures/gantt/a0003.puml"
);
reference_test!(
    reference_fixtures_json_json_escaped_puml,
    "fixtures/json/json_escaped.puml"
);
reference_test!(
    reference_fixtures_mindmap_jaws12_puml,
    "fixtures/mindmap/jaws12.puml"
);
reference_test!(
    reference_fixtures_misc_a0004_puml,
    "fixtures/misc/a0004.puml"
);
reference_test!(
    reference_fixtures_misc_creole_back001_puml,
    "fixtures/misc/creole_back001.puml"
);
reference_test!(
    reference_fixtures_misc_creole_font001_puml,
    "fixtures/misc/creole_font001.puml"
);
reference_test!(
    reference_fixtures_misc_creole_mixed001_puml,
    "fixtures/misc/creole_mixed001.puml"
);
reference_test!(
    reference_fixtures_misc_creole_note001_puml,
    "fixtures/misc/creole_note001.puml"
);
reference_test!(
    reference_fixtures_misc_creole_sup_sub001_puml,
    "fixtures/misc/creole_sup_sub001.puml"
);
reference_test!(
    reference_fixtures_misc_deployment_on_name_puml,
    "fixtures/misc/deployment_on_name.puml"
);
reference_test!(
    reference_fixtures_misc_link_url_tooltip_04_puml,
    "fixtures/misc/link_url_tooltip_04.puml"
);
reference_test!(
    reference_fixtures_misc_link_url_tooltip_05_puml,
    "fixtures/misc/link_url_tooltip_05.puml"
);
reference_test!(
    reference_fixtures_misc_meta_title_header_footer_puml,
    "fixtures/misc/meta_title_header_footer.puml"
);
reference_test!(
    reference_fixtures_misc_skinparam_class001_puml,
    "fixtures/misc/skinparam_class001.puml"
);
reference_test!(
    reference_fixtures_misc_skinparam_colors001_puml,
    "fixtures/misc/skinparam_colors001.puml"
);
reference_test!(
    reference_fixtures_misc_skinparam_font001_puml,
    "fixtures/misc/skinparam_font001.puml"
);
reference_test!(
    reference_fixtures_misc_skinparam_handwritten001_puml,
    "fixtures/misc/skinparam_handwritten001.puml"
);
reference_test!(
    reference_fixtures_misc_skinparam_monochrome001_puml,
    "fixtures/misc/skinparam_monochrome001.puml"
);
reference_test!(
    reference_fixtures_misc_skinparam_roundcorner001_puml,
    "fixtures/misc/skinparam_roundcorner001.puml"
);
reference_test!(
    reference_fixtures_misc_skinparam_sequence001_puml,
    "fixtures/misc/skinparam_sequence001.puml"
);
reference_test!(
    reference_fixtures_misc_xmi0000_puml,
    "fixtures/misc/xmi0000.puml"
);
reference_test!(
    reference_fixtures_nonreg_graphml_GML0000_puml,
    "fixtures/nonreg/graphml/GML0000.puml"
);
reference_test!(
    reference_fixtures_nonreg_graphml_GML0001_puml,
    "fixtures/nonreg/graphml/GML0001.puml"
);
reference_test!(
    reference_fixtures_nonreg_scxml_SCXML0001_puml,
    "fixtures/nonreg/scxml/SCXML0001.puml"
);
reference_test!(
    reference_fixtures_nonreg_scxml_SCXML0002_puml,
    "fixtures/nonreg/scxml/SCXML0002.puml"
);
reference_test!(
    reference_fixtures_nonreg_scxml_SCXML0003_puml,
    "fixtures/nonreg/scxml/SCXML0003.puml"
);
reference_test!(
    reference_fixtures_nonreg_scxml_SCXML0004_puml,
    "fixtures/nonreg/scxml/SCXML0004.puml"
);
reference_test!(
    reference_fixtures_nonreg_scxml_SCXML0005_puml,
    "fixtures/nonreg/scxml/SCXML0005.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_A0000_puml,
    "fixtures/nonreg/simple/A0000.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_A0001_puml,
    "fixtures/nonreg/simple/A0001.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_A0002_puml,
    "fixtures/nonreg/simple/A0002.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_A0003_puml,
    "fixtures/nonreg/simple/A0003.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_A0004_puml,
    "fixtures/nonreg/simple/A0004.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_A0005_puml,
    "fixtures/nonreg/simple/A0005.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_A0006_puml,
    "fixtures/nonreg/simple/A0006.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_ChenMovie_puml,
    "fixtures/nonreg/simple/ChenMovie.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_ChenMovieAlias_puml,
    "fixtures/nonreg/simple/ChenMovieAlias.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_ChenMovieExtended_puml,
    "fixtures/nonreg/simple/ChenMovieExtended.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_ChenRankDir_puml,
    "fixtures/nonreg/simple/ChenRankDir.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_ComponentExtraArrows_0001_puml,
    "fixtures/nonreg/simple/ComponentExtraArrows_0001.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_HideShow001_puml,
    "fixtures/nonreg/simple/HideShow001.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_HideShow002_puml,
    "fixtures/nonreg/simple/HideShow002.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_HideShow003_puml,
    "fixtures/nonreg/simple/HideShow003.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_HideShow004_puml,
    "fixtures/nonreg/simple/HideShow004.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_QualifiedAssoc001_puml,
    "fixtures/nonreg/simple/QualifiedAssoc001.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_QualifiedAssoc002_puml,
    "fixtures/nonreg/simple/QualifiedAssoc002.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceArrows_0001_puml,
    "fixtures/nonreg/simple/SequenceArrows_0001.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceArrows_0002_puml,
    "fixtures/nonreg/simple/SequenceArrows_0002.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLayout_0001_puml,
    "fixtures/nonreg/simple/SequenceLayout_0001.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLayout_0001b_puml,
    "fixtures/nonreg/simple/SequenceLayout_0001b.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLayout_0001c_puml,
    "fixtures/nonreg/simple/SequenceLayout_0001c.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLayout_0002_puml,
    "fixtures/nonreg/simple/SequenceLayout_0002.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLayout_0003_puml,
    "fixtures/nonreg/simple/SequenceLayout_0003.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLayout_0004_puml,
    "fixtures/nonreg/simple/SequenceLayout_0004.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLayout_0005_puml,
    "fixtures/nonreg/simple/SequenceLayout_0005.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLayout_0005b_puml,
    "fixtures/nonreg/simple/SequenceLayout_0005b.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLayout_0006_puml,
    "fixtures/nonreg/simple/SequenceLayout_0006.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLeftMessageAndActiveLifeLines_0001_puml,
    "fixtures/nonreg/simple/SequenceLeftMessageAndActiveLifeLines_0001.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLeftMessageAndActiveLifeLines_0002_puml,
    "fixtures/nonreg/simple/SequenceLeftMessageAndActiveLifeLines_0002.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_SequenceLeftMessageAndActiveLifeLines_0003_puml,
    "fixtures/nonreg/simple/SequenceLeftMessageAndActiveLifeLines_0003.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozAltElseParallel_0001_puml,
    "fixtures/nonreg/simple/TeozAltElseParallel_0001.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozAltElseParallel_0002_puml,
    "fixtures/nonreg/simple/TeozAltElseParallel_0002.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozAltElseParallel_0003_puml,
    "fixtures/nonreg/simple/TeozAltElseParallel_0003.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozAltElseParallel_0004_puml,
    "fixtures/nonreg/simple/TeozAltElseParallel_0004.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozAltElseParallel_0005_puml,
    "fixtures/nonreg/simple/TeozAltElseParallel_0005.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozAltElseParallel_0006_puml,
    "fixtures/nonreg/simple/TeozAltElseParallel_0006.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozTimelineIssues_0001_puml,
    "fixtures/nonreg/simple/TeozTimelineIssues_0001.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozTimelineIssues_0002_puml,
    "fixtures/nonreg/simple/TeozTimelineIssues_0002.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozTimelineIssues_0003_puml,
    "fixtures/nonreg/simple/TeozTimelineIssues_0003.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozTimelineIssues_0004_puml,
    "fixtures/nonreg/simple/TeozTimelineIssues_0004.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozTimelineIssues_0005_puml,
    "fixtures/nonreg/simple/TeozTimelineIssues_0005.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozTimelineIssues_0006_puml,
    "fixtures/nonreg/simple/TeozTimelineIssues_0006.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozTimelineIssues_0007_puml,
    "fixtures/nonreg/simple/TeozTimelineIssues_0007.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozTimelineIssues_0008_puml,
    "fixtures/nonreg/simple/TeozTimelineIssues_0008.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TeozTimelineIssues_0009_puml,
    "fixtures/nonreg/simple/TeozTimelineIssues_0009.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TimingMessageArrowFont_0001_puml,
    "fixtures/nonreg/simple/TimingMessageArrowFont_0001.puml"
);
reference_test!(
    reference_fixtures_nonreg_simple_TimingMessageArrowFont_0002_puml,
    "fixtures/nonreg/simple/TimingMessageArrowFont_0002.puml"
);
reference_test!(
    reference_fixtures_nonreg_svg_SVG0001_puml,
    "fixtures/nonreg/svg/SVG0001.puml"
);
reference_test!(
    reference_fixtures_nonreg_svg_SVG0002_puml,
    "fixtures/nonreg/svg/SVG0002.puml"
);
reference_test!(
    reference_fixtures_nonreg_svg_SVG0003_puml,
    "fixtures/nonreg/svg/SVG0003.puml"
);
reference_test!(
    reference_fixtures_nonreg_svg_SVG0004_Smetana_puml,
    "fixtures/nonreg/svg/SVG0004_Smetana.puml"
);
reference_test!(
    reference_fixtures_nonreg_svg_SVG0004_Svek_puml,
    "fixtures/nonreg/svg/SVG0004_Svek.puml"
);
reference_test!(
    reference_fixtures_nonreg_svg_SVG0005_Smetana_puml,
    "fixtures/nonreg/svg/SVG0005_Smetana.puml"
);
reference_test!(
    reference_fixtures_nonreg_svg_SVG0005_Svek_puml,
    "fixtures/nonreg/svg/SVG0005_Svek.puml"
);
reference_test!(
    reference_fixtures_nonreg_svg_SVG0006_Svek_puml,
    "fixtures/nonreg/svg/SVG0006_Svek.puml"
);
reference_test!(
    reference_fixtures_nonreg_xmi_clazz_XMI0000_puml,
    "fixtures/nonreg/xmi/clazz/XMI0000.puml"
);
reference_test!(
    reference_fixtures_nonreg_xmi_clazz_XMI0002_puml,
    "fixtures/nonreg/xmi/clazz/XMI0002.puml"
);
reference_test!(
    reference_fixtures_nonreg_xmi_clazz_XMI0003_puml,
    "fixtures/nonreg/xmi/clazz/XMI0003.puml"
);
reference_test!(
    reference_fixtures_nonreg_xmi_clazz_XMI0004_puml,
    "fixtures/nonreg/xmi/clazz/XMI0004.puml"
);
reference_test!(
    reference_fixtures_nonreg_xmi_component_XMI0001_puml,
    "fixtures/nonreg/xmi/component/XMI0001.puml"
);
reference_test!(
    reference_fixtures_nwdiag_basic_puml,
    "fixtures/nwdiag/basic.puml"
);
reference_test!(
    reference_fixtures_object_basic_puml,
    "fixtures/object/basic.puml"
);
reference_test!(
    reference_fixtures_object_fields_puml,
    "fixtures/object/fields.puml"
);
reference_test!(
    reference_fixtures_object_map_puml,
    "fixtures/object/map.puml"
);
reference_test!(
    reference_fixtures_preprocessor_builtin_newline_puml,
    "fixtures/preprocessor/builtin_newline.puml"
);
reference_test!(
    reference_fixtures_preprocessor_deployment_mono_multi_line_puml,
    "fixtures/preprocessor/deployment_mono_multi_line.puml"
);
reference_test!(
    reference_fixtures_preprocessor_jaws1_puml,
    "fixtures/preprocessor/jaws1.puml"
);
reference_test!(
    reference_fixtures_preprocessor_jaws3_puml,
    "fixtures/preprocessor/jaws3.puml"
);
reference_test!(
    reference_fixtures_preprocessor_jaws6_puml,
    "fixtures/preprocessor/jaws6.puml"
);
reference_test!(
    reference_fixtures_preprocessor_jaws7_puml,
    "fixtures/preprocessor/jaws7.puml"
);
reference_test!(
    reference_fixtures_preprocessor_jaws8_puml,
    "fixtures/preprocessor/jaws8.puml"
);
reference_test!(
    reference_fixtures_preprocessor_jaws9_puml,
    "fixtures/preprocessor/jaws9.puml"
);
reference_test!(
    reference_fixtures_preprocessor_preproc_functionparam_line_continuation_puml,
    "fixtures/preprocessor/preproc_functionparam_line_continuation.puml"
);
reference_test!(
    reference_fixtures_preprocessor_seq_mono_line_puml,
    "fixtures/preprocessor/seq_mono_line.puml"
);
reference_test!(
    reference_fixtures_preprocessor_sequencearrows_0001_puml,
    "fixtures/preprocessor/sequencearrows_0001.puml"
);
reference_test!(
    reference_fixtures_preprocessor_sequencearrows_0002_puml,
    "fixtures/preprocessor/sequencearrows_0002.puml"
);
reference_test!(
    reference_fixtures_preprocessor_sequencelayout_0004_puml,
    "fixtures/preprocessor/sequencelayout_0004.puml"
);
reference_test!(
    reference_fixtures_preprocessor_sequencelayout_0005_puml,
    "fixtures/preprocessor/sequencelayout_0005.puml"
);
reference_test!(
    reference_fixtures_preprocessor_sequencelayout_0005b_puml,
    "fixtures/preprocessor/sequencelayout_0005b.puml"
);
reference_test!(
    reference_fixtures_preprocessor_sequenceleftmessageandactivelifelines_0001_puml,
    "fixtures/preprocessor/sequenceleftmessageandactivelifelines_0001.puml"
);
reference_test!(
    reference_fixtures_preprocessor_subdiagram_theme_01_puml,
    "fixtures/preprocessor/subdiagram_theme_01.puml"
);
reference_test!(
    reference_fixtures_preprocessor_svg0002_puml,
    "fixtures/preprocessor/svg0002.puml"
);
reference_test!(
    reference_fixtures_preprocessor_svg0004_smetana_puml,
    "fixtures/preprocessor/svg0004_smetana.puml"
);
reference_test!(
    reference_fixtures_preprocessor_svg0004_svek_puml,
    "fixtures/preprocessor/svg0004_svek.puml"
);
reference_test!(
    reference_fixtures_preprocessor_svg0005_smetana_puml,
    "fixtures/preprocessor/svg0005_smetana.puml"
);
reference_test!(
    reference_fixtures_preprocessor_svg0005_svek_puml,
    "fixtures/preprocessor/svg0005_svek.puml"
);
reference_test!(
    reference_fixtures_preprocessor_svg0006_svek_puml,
    "fixtures/preprocessor/svg0006_svek.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teozaltelseparallel_0001_puml,
    "fixtures/preprocessor/teozaltelseparallel_0001.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teozaltelseparallel_0002_puml,
    "fixtures/preprocessor/teozaltelseparallel_0002.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teozaltelseparallel_0003_puml,
    "fixtures/preprocessor/teozaltelseparallel_0003.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teozaltelseparallel_0004_puml,
    "fixtures/preprocessor/teozaltelseparallel_0004.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teozaltelseparallel_0005_puml,
    "fixtures/preprocessor/teozaltelseparallel_0005.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teozaltelseparallel_0006_puml,
    "fixtures/preprocessor/teozaltelseparallel_0006.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teoztimelineissues_0001_puml,
    "fixtures/preprocessor/teoztimelineissues_0001.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teoztimelineissues_0002_puml,
    "fixtures/preprocessor/teoztimelineissues_0002.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teoztimelineissues_0003_puml,
    "fixtures/preprocessor/teoztimelineissues_0003.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teoztimelineissues_0004_puml,
    "fixtures/preprocessor/teoztimelineissues_0004.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teoztimelineissues_0005_puml,
    "fixtures/preprocessor/teoztimelineissues_0005.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teoztimelineissues_0006_puml,
    "fixtures/preprocessor/teoztimelineissues_0006.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teoztimelineissues_0007_puml,
    "fixtures/preprocessor/teoztimelineissues_0007.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teoztimelineissues_0008_puml,
    "fixtures/preprocessor/teoztimelineissues_0008.puml"
);
reference_test!(
    reference_fixtures_preprocessor_teoztimelineissues_0009_puml,
    "fixtures/preprocessor/teoztimelineissues_0009.puml"
);
reference_test!(
    reference_fixtures_salt_basic_puml,
    "fixtures/salt/basic.puml"
);
reference_test!(
    reference_fixtures_sequence_a0000_puml,
    "fixtures/sequence/a0000.puml"
);
reference_test!(
    reference_fixtures_sequence_a0001_puml,
    "fixtures/sequence/a0001.puml"
);
reference_test!(
    reference_fixtures_sequence_a0006_puml,
    "fixtures/sequence/a0006.puml"
);
reference_test!(
    reference_fixtures_sequence_intermediatetest_0000_puml,
    "fixtures/sequence/intermediatetest_0000.puml"
);
reference_test!(
    reference_fixtures_sequence_jaws10_puml,
    "fixtures/sequence/jaws10.puml"
);
reference_test!(
    reference_fixtures_sequence_jaws11_puml,
    "fixtures/sequence/jaws11.puml"
);
reference_test!(
    reference_fixtures_sequence_jaws2_puml,
    "fixtures/sequence/jaws2.puml"
);
reference_test!(
    reference_fixtures_sequence_jaws4_puml,
    "fixtures/sequence/jaws4.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_alt001_puml,
    "fixtures/sequence/seq_alt001.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_autonumber001_puml,
    "fixtures/sequence/seq_autonumber001.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_break001_puml,
    "fixtures/sequence/seq_break001.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_critical001_puml,
    "fixtures/sequence/seq_critical001.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_divider001_puml,
    "fixtures/sequence/seq_divider001.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_group001_puml,
    "fixtures/sequence/seq_group001.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_loop001_puml,
    "fixtures/sequence/seq_loop001.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_nested001_puml,
    "fixtures/sequence/seq_nested001.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_opt001_puml,
    "fixtures/sequence/seq_opt001.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_par001_puml,
    "fixtures/sequence/seq_par001.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_participants001_puml,
    "fixtures/sequence/seq_participants001.puml"
);
reference_test!(
    reference_fixtures_sequence_seq_ref001_puml,
    "fixtures/sequence/seq_ref001.puml"
);
reference_test!(
    reference_fixtures_sequence_sequencelayout_0001_puml,
    "fixtures/sequence/sequencelayout_0001.puml"
);
reference_test!(
    reference_fixtures_sequence_sequencelayout_0001b_puml,
    "fixtures/sequence/sequencelayout_0001b.puml"
);
reference_test!(
    reference_fixtures_sequence_sequencelayout_0001c_puml,
    "fixtures/sequence/sequencelayout_0001c.puml"
);
reference_test!(
    reference_fixtures_sequence_sequencelayout_0002_puml,
    "fixtures/sequence/sequencelayout_0002.puml"
);
reference_test!(
    reference_fixtures_sequence_sequencelayout_0003_puml,
    "fixtures/sequence/sequencelayout_0003.puml"
);
reference_test!(
    reference_fixtures_sequence_sequencelayout_0006_puml,
    "fixtures/sequence/sequencelayout_0006.puml"
);
reference_test!(
    reference_fixtures_sequence_sequenceleftmessageandactivelifelines_0002_puml,
    "fixtures/sequence/sequenceleftmessageandactivelifelines_0002.puml"
);
reference_test!(
    reference_fixtures_sequence_sequenceleftmessageandactivelifelines_0003_puml,
    "fixtures/sequence/sequenceleftmessageandactivelifelines_0003.puml"
);
reference_test!(
    reference_fixtures_sequence_svg0001_puml,
    "fixtures/sequence/svg0001.puml"
);
reference_test!(
    reference_fixtures_sequence_svg0003_puml,
    "fixtures/sequence/svg0003.puml"
);
reference_test!(
    reference_fixtures_sequence_test_0_puml,
    "fixtures/sequence/test_0.puml"
);
reference_test!(
    reference_fixtures_sprite_azureSVG_puml,
    "fixtures/sprite/azureSVG.puml"
);
reference_test!(
    reference_fixtures_sprite_linearGradientSpreadPad_puml,
    "fixtures/sprite/linearGradientSpreadPad.puml"
);
reference_test!(
    reference_fixtures_sprite_linearGradientSpreadReflect_puml,
    "fixtures/sprite/linearGradientSpreadReflect.puml"
);
reference_test!(
    reference_fixtures_sprite_linearGradientSpreadRepeat_puml,
    "fixtures/sprite/linearGradientSpreadRepeat.puml"
);
reference_test!(
    reference_fixtures_sprite_styleFontWeightRoboto_puml,
    "fixtures/sprite/styleFontWeightRoboto.puml"
);
reference_test!(
    reference_fixtures_sprite_svg2Groups_puml,
    "fixtures/sprite/svg2Groups.puml"
);
reference_test!(
    reference_fixtures_sprite_svg2GroupsInlineStyled_puml,
    "fixtures/sprite/svg2GroupsInlineStyled.puml"
);
reference_test!(
    reference_fixtures_sprite_svg2GroupsWithStyle_puml,
    "fixtures/sprite/svg2GroupsWithStyle.puml"
);
reference_test!(
    reference_fixtures_sprite_svgDiagonalGradientBLTR_puml,
    "fixtures/sprite/svgDiagonalGradientBLTR.puml"
);
reference_test!(
    reference_fixtures_sprite_svgDiagonalGradientBLTRMonochrome_puml,
    "fixtures/sprite/svgDiagonalGradientBLTRMonochrome.puml"
);
reference_test!(
    reference_fixtures_sprite_svgDiagonalGradientTLBR_puml,
    "fixtures/sprite/svgDiagonalGradientTLBR.puml"
);
reference_test!(
    reference_fixtures_sprite_svgEmbeddedPNG_puml,
    "fixtures/sprite/svgEmbeddedPNG.puml"
);
reference_test!(
    reference_fixtures_sprite_svgFillColourTest_2174_puml,
    "fixtures/sprite/svgFillColourTest_2174.puml"
);
reference_test!(
    reference_fixtures_sprite_svgFontWeightMultiWeight_puml,
    "fixtures/sprite/svgFontWeightMultiWeight.puml"
);
reference_test!(
    reference_fixtures_sprite_svgFontWeightStandardFonts_puml,
    "fixtures/sprite/svgFontWeightStandardFonts.puml"
);
reference_test!(
    reference_fixtures_sprite_svgLinearGradientCircle_puml,
    "fixtures/sprite/svgLinearGradientCircle.puml"
);
reference_test!(
    reference_fixtures_sprite_svgPolygonStar_puml,
    "fixtures/sprite/svgPolygonStar.puml"
);
reference_test!(
    reference_fixtures_sprite_svgRadialGradient_puml,
    "fixtures/sprite/svgRadialGradient.puml"
);
reference_test!(
    reference_fixtures_sprite_svgRedCircle_puml,
    "fixtures/sprite/svgRedCircle.puml"
);
reference_test!(
    reference_fixtures_sprite_svgRedEllipse_puml,
    "fixtures/sprite/svgRedEllipse.puml"
);
reference_test!(
    reference_fixtures_sprite_svgRedLine_puml,
    "fixtures/sprite/svgRedLine.puml"
);
reference_test!(
    reference_fixtures_sprite_svgRedPolyLine_puml,
    "fixtures/sprite/svgRedPolyLine.puml"
);
reference_test!(
    reference_fixtures_sprite_svgRedRect_puml,
    "fixtures/sprite/svgRedRect.puml"
);
reference_test!(
    reference_fixtures_sprite_svgRedRectLinearGradient_puml,
    "fixtures/sprite/svgRedRectLinearGradient.puml"
);
reference_test!(
    reference_fixtures_sprite_svgRedStroke_puml,
    "fixtures/sprite/svgRedStroke.puml"
);
reference_test!(
    reference_fixtures_sprite_svgRedText_puml,
    "fixtures/sprite/svgRedText.puml"
);
reference_test!(
    reference_fixtures_sprite_svgTextAnchor_puml,
    "fixtures/sprite/svgTextAnchor.puml"
);
reference_test!(
    reference_fixtures_sprite_svgTextBold_puml,
    "fixtures/sprite/svgTextBold.puml"
);
reference_test!(
    reference_fixtures_sprite_svgTextDecoration_puml,
    "fixtures/sprite/svgTextDecoration.puml"
);
reference_test!(
    reference_fixtures_sprite_svgTextItalic_puml,
    "fixtures/sprite/svgTextItalic.puml"
);
reference_test!(
    reference_fixtures_sprite_svgTextStyleAttr_puml,
    "fixtures/sprite/svgTextStyleAttr.puml"
);
reference_test!(
    reference_fixtures_sprite_svgTransformGroup_puml,
    "fixtures/sprite/svgTransformGroup.puml"
);
reference_test!(
    reference_fixtures_sprite_svgTransformMatrix_puml,
    "fixtures/sprite/svgTransformMatrix.puml"
);
reference_test!(
    reference_fixtures_sprite_svgTransformRotate_puml,
    "fixtures/sprite/svgTransformRotate.puml"
);
reference_test!(
    reference_fixtures_sprite_svgTransformScale_puml,
    "fixtures/sprite/svgTransformScale.puml"
);
reference_test!(
    reference_fixtures_sprite_svgTransformTranslate_puml,
    "fixtures/sprite/svgTransformTranslate.puml"
);
reference_test!(
    reference_fixtures_sprite_svgUseDefs_puml,
    "fixtures/sprite/svgUseDefs.puml"
);
reference_test!(
    reference_fixtures_sprite_svgVerticalGradient_puml,
    "fixtures/sprite/svgVerticalGradient.puml"
);
reference_test!(
    reference_fixtures_sprite_testGradientSprite_puml,
    "fixtures/sprite/testGradientSprite.puml"
);
reference_test!(
    reference_fixtures_sprite_testPolylineSprites_puml,
    "fixtures/sprite/testPolylineSprites.puml"
);
reference_test!(
    reference_fixtures_state_scxml0001_puml,
    "fixtures/state/scxml0001.puml"
);
reference_test!(
    reference_fixtures_state_scxml0002_puml,
    "fixtures/state/scxml0002.puml"
);
reference_test!(
    reference_fixtures_state_scxml0003_puml,
    "fixtures/state/scxml0003.puml"
);
reference_test!(
    reference_fixtures_state_scxml0004_puml,
    "fixtures/state/scxml0004.puml"
);
reference_test!(
    reference_fixtures_state_scxml0005_puml,
    "fixtures/state/scxml0005.puml"
);
reference_test!(
    reference_fixtures_state_state_choice001_puml,
    "fixtures/state/state_choice001.puml"
);
reference_test!(
    reference_fixtures_state_state_concurrent001_puml,
    "fixtures/state/state_concurrent001.puml"
);
reference_test!(
    reference_fixtures_state_state_fork001_puml,
    "fixtures/state/state_fork001.puml"
);
reference_test!(
    reference_fixtures_state_state_history001_puml,
    "fixtures/state/state_history001.puml"
);
reference_test!(
    reference_fixtures_state_state_monoline_01_puml,
    "fixtures/state/state_monoline_01.puml"
);
reference_test!(
    reference_fixtures_state_state_monoline_02_puml,
    "fixtures/state/state_monoline_02.puml"
);
reference_test!(
    reference_fixtures_state_state_monoline_03_puml,
    "fixtures/state/state_monoline_03.puml"
);
reference_test!(
    reference_fixtures_state_state_note001_puml,
    "fixtures/state/state_note001.puml"
);
reference_test!(
    reference_fixtures_timing_timingmessagearrowfont_0001_puml,
    "fixtures/timing/timingmessagearrowfont_0001.puml"
);
reference_test!(
    reference_fixtures_timing_timingmessagearrowfont_0002_puml,
    "fixtures/timing/timingmessagearrowfont_0002.puml"
);
reference_test!(
    reference_fixtures_usecase_basic_puml,
    "fixtures/usecase/basic.puml"
);
reference_test!(
    reference_fixtures_usecase_boundary_puml,
    "fixtures/usecase/boundary.puml"
);
reference_test!(
    reference_fixtures_usecase_colon_actor_puml,
    "fixtures/usecase/colon_actor.puml"
);
reference_test!(
    reference_fixtures_wbs_link_url_tooltip_01_puml,
    "fixtures/wbs/link_url_tooltip_01.puml"
);
reference_test!(
    reference_fixtures_wbs_link_url_tooltip_02_puml,
    "fixtures/wbs/link_url_tooltip_02.puml"
);
reference_test!(
    reference_fixtures_wbs_link_url_tooltip_03_puml,
    "fixtures/wbs/link_url_tooltip_03.puml"
);
reference_test!(
    reference_fixtures_wbs_wbs_arrow_puml,
    "fixtures/wbs/wbs_arrow.puml"
);
reference_test!(
    reference_fixtures_wbs_wbs_direction_puml,
    "fixtures/wbs/wbs_direction.puml"
);
reference_test!(
    reference_fixtures_yaml_basic_puml,
    "fixtures/yaml/basic.puml"
);

reference_test!(
    reference_fixtures_packet_basic_puml,
    "fixtures/packet/basic.puml"
);
reference_test!(
    reference_fixtures_git_basic_puml,
    "fixtures/git/basic.puml"
);

// Total: 298 reference tests
