@startuml
!pragma teoz true

participant "Random Name" as foo

hide footbox

  opt message received
    alt REQUEST
        bossrpcp -> bossrpcp : request
    else RESPONSE
        bossrpcp -> bossrpcp : respond
    else AGAIN
     bossrpcp -> bossrpcp : request
    end
end
& foo -> foo : test

@enduml
